import{readFileSync}from'node:fs';import{Box3,DoubleSide,Mesh,Object3D,Raycaster,Vector3}from'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{describe,expect,it}from'vitest';
type V=[number,number,number];type Eye={points:V[];arcRadius:number};type Design={ringRadius:number;barRadius:number;ropeRadius:number;upperEye:Eye;strands:{eye:Eye;line:[V,V]}[];hoistEnd:V;productionReady:boolean};
const folder='artifacts/eiffel-master-link-2026-09-08/',design=JSON.parse(readFileSync(folder+'design.json','utf8'))as Design,eyes=[{id:'upper-rope-eye',eye:design.upperEye},...design.strands.map((s,i)=>({id:`lower-rope-eye-${i}`,eye:s.eye}))],paths=[...eyes.map(x=>({id:x.id,points:x.eye.points})),...design.strands.map((s,i)=>({id:`sling-leg-${i}`,points:s.line}))];
const mix=(a:V,b:V,t:number):V=>a.map((v,i)=>v+(b[i]!-v)*t)as V,torusDistance=(p:V)=>Math.hypot(Math.hypot(p[0],p[1])-design.ringRadius,p[2]),sub=(a:V,b:V):V=>a.map((v,i)=>v-b[i]!)as V,dot=(a:V,b:V)=>a.reduce((s,v,i)=>s+v*b[i]!,0);
function segmentDistance(p1:V,q1:V,p2:V,q2:V){const u=sub(q1,p1),v=sub(q2,p2),w=sub(p1,p2),a=dot(u,u),b=dot(u,v),c=dot(v,v),d=dot(u,w),e=dot(v,w),den=a*c-b*b;let s=den<1e-15?0:(b*e-c*d)/den;s=Math.max(0,Math.min(1,s));let t=Math.max(0,Math.min(1,c?(b*s+e)/c:0));s=Math.max(0,Math.min(1,a?(b*t-d)/a:0));return Math.hypot(...sub(mix(p1,q1,s),mix(p2,q2,t)));}
const load=async()=>{const bytes=readFileSync(folder+'model/master-link.glb');return(await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;},dispose=(root:Object3D)=>root.traverse(o=>{if(o instanceof Mesh)o.geometry.dispose();});

describe('Eiffel master-link and rope eyes',()=>{
 it('keeps every authored eye tangent to the analytic forged torus',()=>{const required=design.barRadius+design.ropeRadius,failures:string[]=[];for(const{id,eye}of eyes){expect(eye.arcRadius,id).toBeGreaterThan(required);let minimum=Infinity;for(let i=0;i<eye.points.length-1;i++)for(let j=0;j<=200;j++)minimum=Math.min(minimum,torusDistance(mix(eye.points[i]!,eye.points[i+1]!,j/200)));if(minimum<required-1e-12)failures.push(`${id}:${minimum}`);expect(Math.abs(minimum-required),id).toBeLessThan(1e-12);}expect(failures).toEqual([]);});

 it('keeps all distinct eyes and strand tails apart outside four named splices',()=>{const failures:string[]=[],separations:{a:string;b:string;distance:number}[]=[];let excluded=0;for(let i=0;i<paths.length;i++)for(let j=i+1;j<paths.length;j++){const a=paths[i]!,b=paths[j]!,lowerA=/lower-rope-eye-(\d)/.exec(a.id)?.[1],lowerB=/lower-rope-eye-(\d)/.exec(b.id)?.[1],legA=/sling-leg-(\d)/.exec(a.id)?.[1],legB=/sling-leg-(\d)/.exec(b.id)?.[1],splice=(lowerA!==undefined&&legB!==undefined&&lowerA===legB)||(lowerB!==undefined&&legA!==undefined&&lowerB===legA);if(splice){excluded++;continue;}let minimum=Infinity;for(let x=0;x<a.points.length-1;x++)for(let y=0;y<b.points.length-1;y++)minimum=Math.min(minimum,segmentDistance(a.points[x]!,a.points[x+1]!,b.points[y]!,b.points[y+1]!));separations.push({a:a.id,b:b.id,distance:minimum});if(minimum<2*design.ropeRadius-1e-12)failures.push(`${a.id}:${b.id}:${minimum}`);}expect(excluded).toBe(4);expect(separations).toHaveLength(32);const distinctLegs=separations.filter(x=>x.a.startsWith('sling-leg')&&x.b.startsWith('sling-leg'));expect(Math.min(...distinctLegs.map(x=>x.distance))).toBeCloseTo(.1483223708878469,12);expect(failures).toEqual([]);});

 it('exports exactly the authored roles, endpoints and torus contact clearance',async()=>{const root=await load();try{root.updateMatrixWorld(true);const roles=new Map<string,Mesh>();root.traverse(o=>{if(o instanceof Mesh)roles.set(String(o.userData.wf_role),o);});const expected=['master-link','upper-rope-eye',...design.strands.flatMap((_,i)=>[`lower-rope-eye-${i}`,`sling-leg-${i}`])];expect([...roles.keys()].sort()).toEqual([...expected].sort());expect(roles.size).toBe(10);const master=roles.get('master-link')!,bounds=new Box3().setFromObject(master);for(const[a,b]of[[bounds.min.x,-.148],[bounds.max.x,.148],[bounds.min.y,-.148],[bounds.max.y,.148],[bounds.min.z,-.018],[bounds.max.z,.018]])expect(Math.abs(a!-b!)).toBeLessThan(2e-5);for(const material of(Array.isArray(master.material)?master.material:[master.material]))material.side=DoubleSide;
   const failures:string[]=[],ray=new Raycaster();for(const path of paths){const mesh=roles.get(path.id)!,box=new Box3().setFromObject(mesh).expandByScalar(2e-5);for(const[index,p]of path.points.entries())if(!box.containsPoint(new Vector3(...p)))failures.push(`${path.id}:endpoint-${index}`);}for(const{id,eye}of eyes){let closest:V=[0,0,0],minimum=Infinity;for(let i=0;i<eye.points.length-1;i++)for(let j=0;j<=200;j++){const p=mix(eye.points[i]!,eye.points[i+1]!,j/200),d=torusDistance(p);if(d<minimum){minimum=d;closest=p;}}const point=new Vector3(...closest),rho=Math.hypot(point.x,point.y),centerline=new Vector3(design.ringRadius*point.x/rho,design.ringRadius*point.y/rho,0),direction=point.clone().sub(centerline).normalize();ray.set(centerline,direction);const hit=ray.intersectObject(master,false)[0],clearance=hit?minimum-hit.distance-design.ropeRadius:-Infinity;if(clearance<-2e-5)failures.push(`${id}:actual:${clearance}`);}expect(failures).toEqual([]);
  }finally{dispose(root);}},30_000);

 it('records the reduced but positive raised-sheave headroom',()=>{const prior=.6374996934179791;expect(design.hoistEnd).toEqual([0,.25,0]);expect(prior-design.hoistEnd[1]).toBeCloseTo(.3874996934179791,12);expect(design.productionReady).toBe(false);});
});
