import{it,expect}from'vitest';import{sampleEiffelSummitWorkerAccess}from'../src/engine/eiffelSummitWorkerAccess';import{EIFFEL_SUMMIT_RUNG_SOLE0,eiffelSummitWorkerRig,sampleEiffelSummitCrankWorker}from'../src/engine/eiffelSummitWorker';
it('has reachable connected limbs and three fixed supported contacts through the access sequence',()=>{for(let i=0;i<=7200;i++){const t=i/100,s=sampleEiffelSummitWorkerAccess(t);expect(()=>eiffelSummitWorkerRig(s.targets)).not.toThrow();expect(s.contacts.length).toBeGreaterThanOrEqual(3);for(let j=0;j<2;j++)if(s.contacts.includes('foot-'+j)){const p=s.targets.feet[j]!;expect(p[2]).toBe(-.4);expect((p[1]-EIFFEL_SUMMIT_RUNG_SOLE0)/.28).toBeCloseTo(Math.round((p[1]-EIFFEL_SUMMIT_RUNG_SOLE0)/.28),7);}}});
it('joins the unchanged crank pose and reverses exactly',()=>{expect(sampleEiffelSummitWorkerAccess(72).targets).toEqual(sampleEiffelSummitCrankWorker(0));const a=sampleEiffelSummitWorkerAccess(23.4);sampleEiffelSummitWorkerAccess(70);expect(sampleEiffelSummitWorkerAccess(23.4)).toEqual(a);});
it('keeps each declared hand contact stationary while the other limb moves',()=>{for(let i=1;i<6400;i++){const a=sampleEiffelSummitWorkerAccess(i/100),b=sampleEiffelSummitWorkerAccess(i/100+.001);if(a.moving!==b.moving)continue;for(let j=0;j<2;j++)if(a.contacts.includes('hand-'+j))expect(b.targets.hands[j]).toEqual(a.targets.hands[j]);}});
it('places soles on actual V9 exported rung surfaces at every settled level',async()=>{
 const {readFileSync}=await import('node:fs');const{GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js');const{Mesh,Raycaster,Vector3,DoubleSide}=await import('three');
 const b=readFileSync('artifacts/eiffel-gin-pole-climb-2026-09-08/model/summit-gin-pole-climb.glb');const root=(await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')).scene;root.updateMatrixWorld(true);
 const meshes:any[]=[];root.traverse(o=>{if(o instanceof Mesh){for(const m of Array.isArray(o.material)?o.material:[o.material])m.side=DoubleSide;if(o.name.startsWith('ladder-rung'))meshes.push(o);}});const ray=new Raycaster();
 for(let i=0;i<=16;i++)for(const foot of sampleEiffelSummitWorkerAccess(i*4).targets.feet){ray.set(new Vector3(foot[0],foot[1]+.05,foot[2]+.1),new Vector3(0,-1,0));const hit=ray.intersectObjects(meshes,false)[0];expect(hit).toBeDefined();expect(hit!.point.y).toBeCloseTo(foot[1],4);}
 root.traverse(o=>{if(o instanceof Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});
});
it('has no pose jump at any limb-release or stance boundary',()=>{for(const t of[...Array.from({length:64},(_,i)=>i+1),68,70,72]){const a=sampleEiffelSummitWorkerAccess(t-1e-6).targets,b=sampleEiffelSummitWorkerAccess(t).targets;for(const [p,q]of[[a.pelvis,b.pelvis],...a.feet.map((p,i)=>[p,b.feet[i]!]),...a.hands.map((p,i)=>[p,b.hands[i]!])])expect(Math.hypot(...p!.map((v,i)=>v-q![i]!))).toBeLessThan(1e-8);}});
it('keeps source palms in contact with the actual rung fronts at settled climb poses',async()=>{
 const{EiffelSummitGinPoleSystem}=await import('../src/render/three/EiffelSummitGinPoleSystem');const{Mesh,Raycaster,Vector3,DoubleSide}=await import('three');const system=new EiffelSummitGinPoleSystem();await system.ready;
 const rungs:any[]=[],hands:any[]=[];system.group.traverse(o=>{if(o instanceof Mesh){for(const m of Array.isArray(o.material)?o.material:[o.material])m.side=DoubleSide;if(o.name.startsWith('ladder-rung'))rungs.push(o);if(o.name.startsWith('pusher_hand-'))hands.push(o);}});const ray=new Raycaster();
 for(let i=0;i<=16;i++){system.updateAccess(i*4);const sample=sampleEiffelSummitWorkerAccess(i*4);for(let j=0;j<2;j++){const p=sample.targets.hands[j]!;ray.set(new Vector3(...p),new Vector3(0,0,1));const palm=ray.intersectObjects(hands,false)[0];ray.set(new Vector3(p[0],p[1],-.6),new Vector3(0,0,1));const rung=ray.intersectObjects(rungs,false)[0];expect(palm).toBeDefined();expect(rung).toBeDefined();expect(palm!.point.z-rung!.point.z).toBeGreaterThanOrEqual(-.00005);}}
 system.dispose();
});
