import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {describe,it,expect} from 'vitest';
import {PerspectiveCamera,Vector3} from 'three';
import envelope from '../src/data/eiffelSummitWorkEnvelope.json';
import pace from '../src/data/eiffelStage63Pace.json';
import type {EiffelKitManifest} from '../src/data/eiffelKitTypes';
import {eiffelSolidBox} from '../src/engine/eiffelOccupancy';
import {EIFFEL_FILM_DURATION,EIFFEL_FILM_STAGE63_FINAL_WAVE_START_SECONDS,EIFFEL_FILM_STAGE63_FINAL_WAVE_END_SECONDS,eiffelFilmShotAt,eiffelFilmAzimuthAt} from '../src/engine/eiffelFilm';
import {EIFFEL_SUMMIT_WORK_CORNERS,EIFFEL_SUMMIT_CONTEXT_CORNERS} from '../src/engine/eiffelSummitCamera';
const start=()=>EIFFEL_FILM_STAGE63_FINAL_WAVE_START_SECONDS,end=()=>EIFFEL_FILM_STAGE63_FINAL_WAVE_END_SECONDS;
function cameraAt(seconds:number,aspect:number){const s=eiffelFilmShotAt(seconds/EIFFEL_FILM_DURATION,aspect),c=new PerspectiveCamera(s.fov,aspect,5,2400);c.position.set(s.target[0]+Math.cos(s.azimuth)*Math.cos(s.pitch)*s.radius,s.target[1]+Math.sin(s.pitch)*s.radius,s.target[2]+Math.sin(s.azimuth)*Math.cos(s.pitch)*s.radius);c.lookAt(new Vector3(...s.target));c.updateMatrixWorld();return c;}
describe('final summit working view',()=>{
 it('is tied to the current manifest and actual simultaneous mast wave',()=>{const bytes=readFileSync('public/models/eiffel-construction-kit/tower-kit.manifest.json');expect(createHash('sha256').update(bytes).digest('hex')).toBe(envelope.manifestSha256);expect(envelope.wave).toBe(pace.representative.wave);expect(envelope.partIds).toContain(pace.representative.partId);expect(end()-start()).toBeGreaterThan(40);});
 it('frames the apparatus together with the upper tower in desktop and portrait',()=>{for(const[width,height]of[[1440,900],[390,844],[320,844]])for(let seconds=start()+4;seconds<=end();seconds+=.5){const camera=cameraAt(seconds,width!/height!);for(const p of [...EIFFEL_SUMMIT_WORK_CORNERS,...EIFFEL_SUMMIT_CONTEXT_CORNERS]){const v=new Vector3(...p).project(camera);expect(Math.abs(v.x),`x ${seconds}`).toBeLessThan(.9);expect(Math.abs(v.y),`y ${seconds}`).toBeLessThan(.9);expect(v.z).toBeGreaterThan(-1);}const p1=new Vector3(0,307.333333,0).project(camera),p2=new Vector3(0,312,0).project(camera);expect(Math.abs(p1.y-p2.y)*height!/2).toBeLessThan(40);}});
 it('keeps a contextual distance through lowering and the first seated frame',()=>{for(const aspect of[1440/900,390/844]){const a=eiffelFilmShotAt((end()-3.6)/EIFFEL_FILM_DURATION,aspect),b=eiffelFilmShotAt(end()/EIFFEL_FILM_DURATION,aspect);expect(b.target).toEqual(a.target);expect(b.radius).toBeGreaterThanOrEqual(210);expect(eiffelFilmShotAt((end()+4)/EIFFEL_FILM_DURATION,aspect).radius).toBeGreaterThan(500);}});
 it('preserves the global orbit and has continuous, reversible entry and recovery',()=>{for(const aspect of[1440/900,390/844])for(const seconds of[start(),start()+4,end(),end()+4]){const a=eiffelFilmShotAt((seconds-1e-6)/EIFFEL_FILM_DURATION,aspect),b=eiffelFilmShotAt((seconds+1e-6)/EIFFEL_FILM_DURATION,aspect);expect(Math.hypot(...a.target.map((v,i)=>v-b.target[i]!))).toBeLessThan(.001);expect(Math.abs(a.radius-b.radius)).toBeLessThan(.001);const mid=eiffelFilmShotAt(seconds/EIFFEL_FILM_DURATION,aspect);expect(mid.azimuth).toBe(eiffelFilmAzimuthAt(seconds/EIFFEL_FILM_DURATION));eiffelFilmShotAt(0,aspect);eiffelFilmShotAt(1,aspect);expect(eiffelFilmShotAt(seconds/EIFFEL_FILM_DURATION,aspect)).toEqual(mid);}});
 it('keeps the complete five-metre near frustum clear of all completed tower solids',()=>{const manifest=JSON.parse(readFileSync('public/models/eiffel-construction-kit/tower-kit.manifest.json','utf8'))as EiffelKitManifest,boxes=manifest.parts.map(p=>eiffelSolidBox(p,p.finalPose));for(const aspect of[1440/900,390/844])for(let seconds=start();seconds<end()+4;seconds+=1){const c=cameraAt(seconds,aspect),p=c.position.toArray(),sphere=5*Math.sqrt(1+Math.tan(c.fov*Math.PI/360)**2*(1+aspect**2));let minimum=Infinity;for(const box of boxes){const delta=p.map((v,i)=>v-box.center[i]!),distance=Math.hypot(...box.axes.map((axis,i)=>Math.max(0,Math.abs(axis.reduce((sum,v,j)=>sum+v*delta[j]!,0))-box.half[i]!)));minimum=Math.min(minimum,distance);}expect(minimum,`near frustum at ${seconds}`).toBeGreaterThan(sphere);}});
});
