import {describe,expect,it}from'vitest';
import {readFileSync}from'node:fs';
import type {EiffelKitManifest}from'../src/data/eiffelKitTypes';
import {createEiffelProductionPlan,sampleEiffelProductionOperation}from'../src/engine/eiffelProductionConstruction';
import {createEiffelPhysicalConstructionClock}from'../src/engine/eiffelPhysicalConstructionClock';
import type{RigidPose,RigidQuat}from'../src/engine/eiffelRigid';
import paceRecord from'../src/data/eiffelStage63Pace.json';
import{createHash}from'node:crypto';

describe('Eiffel bounded physical construction clock',()=>{
 it('preserves simultaneous waves and gives each route phase its physical time',()=>{const q:RigidQuat=[0,0,0,1],turn:RigidQuat=[0,Math.SQRT1_2,0,Math.SQRT1_2],pose=(x:number,y:number,z:number,quaternion:RigidQuat=q):RigidPose=>({position:[x,y,z],quaternion});const op={id:'summit-crown-m072-c002',stage:63,wave:7,start:.8,end:.8001,pickup:pose(0,0,0),clear:pose(0,3,0,turn),waypoint:pose(2,3,0,turn),approach:pose(4,3,0,turn),finalPose:pose(4,2.5,0,turn)};const clock=createEiffelPhysicalConstructionClock([op,op]);expect(clock.selectedWaveCount).toBe(1);const phases=clock.segments.filter(s=>s.wave===7);expect(phases.map(s=>s.phase)).toEqual(['staged','hoist','transfer','lower']);expect(phases[0]!.secondsEnd-phases[0]!.secondsStart).toBeCloseTo(1.5,12);expect(phases[1]!.secondsEnd-phases[1]!.secondsStart).toBeCloseTo(1.5*Math.max(3/.75,(Math.PI/2)/(Math.PI/9)),12);expect(phases[2]!.secondsEnd-phases[2]!.secondsStart).toBeCloseTo(1.5*4/.65,12);expect(phases[3]!.secondsEnd-phases[3]!.secondsStart).toBeCloseTo(3,12);});
 it('is monotone, exactly reversible, deterministic, and leaves unselected time at original speed',()=>{const q=[0,0,0,1]as const,p=(x:number)=>({position:[x,0,0]as[number,number,number],quaternion:q}),op={stage:63,wave:1,start:.8,end:.9,pickup:p(0),clear:p(1),waypoint:p(2),approach:p(3),finalPose:p(4)},clock=createEiffelPhysicalConstructionClock([op]);for(let i=0;i<=2000;i++){const t=i/2000;expect(clock.secondsToProductionT(clock.productionToSeconds(t))).toBeCloseTo(t,11);}expect(clock.productionToSeconds(.4)).toBeCloseTo(24,12);const again=createEiffelPhysicalConstructionClock([op]);expect(again.duration).toBe(clock.duration);expect(again.segments).toEqual(clock.segments);expect(()=>clock.productionToSeconds(NaN)).toThrow(/finite/);});
 it('measures the current stage-63 campaign and reproduces the compact runtime record',()=>{const bytes=readFileSync('public/models/eiffel-construction-kit/tower-kit.manifest.json'),manifest=JSON.parse(bytes.toString())as EiffelKitManifest,plan=createEiffelProductionPlan(manifest),clock=createEiffelPhysicalConstructionClock(plan.operations.map(op=>({...op,id:op.part.id,stage:op.part.stage,finalPose:op.part.finalPose,station:op.station??undefined})));expect(manifest.parts).toHaveLength(13_852);expect(clock.selectedOperationCount).toBe(75);expect(clock.selectedWaveCount).toBe(20);expect(clock.duration).toBeCloseTo(160.42677070385625,10);expect(clock.segments).toEqual(paceRecord.segments);expect(createHash('sha256').update(bytes).digest('hex')).toBe(paceRecord.source.manifestSha256);const last=plan.byPart.get('summit-crown-m072-c002')!,segment=clock.segments.filter(s=>s.wave===last.wave);expect(segment).toHaveLength(4);expect(segment.reduce((sum,s)=>sum+s.secondsEnd-s.secondsStart,0)).toBeGreaterThan(25);},30_000);
 it('bounds actual sampled background motion per frame and the representative wave at review speed',()=>{const manifest=JSON.parse(readFileSync('public/models/eiffel-construction-kit/tower-kit.manifest.json','utf8'))as EiffelKitManifest,plan=createEiffelProductionPlan(manifest),ops=plan.operations.filter(op=>op.part.stage===63),clock=createEiffelPhysicalConstructionClock(plan.operations.map(op=>({...op,id:op.part.id,stage:op.part.stage,finalPose:op.part.finalPose,station:op.station??undefined}))),frame=1/60;for(const op of ops){const start=clock.productionToSeconds(op.start),end=clock.productionToSeconds(op.end),representative=op.wave===paceRecord.representative.wave;for(let seconds=start;seconds<end-1e-9;seconds+=frame){const a=sampleEiffelProductionOperation(op,clock.secondsToProductionT(seconds)).pose,b=sampleEiffelProductionOperation(op,clock.secondsToProductionT(Math.min(end,seconds+frame))).pose,metres=Math.hypot(...a.position.map((value,index)=>value-b.position[index]!)),dot=Math.min(1,Math.abs(a.quaternion.reduce((sum,value,index)=>sum+value*b.quaternion[index]!,0)));expect(metres,`${op.part.id}@${seconds}`).toBeLessThanOrEqual(representative?.75/60+.0002:.2502);expect(2*Math.acos(dot),`${op.part.id} rotation@${seconds}`).toBeLessThanOrEqual(representative?(Math.PI/9)/60+.0002:Math.PI/36+.0002);}}},30_000);
 it('rejects invalid rates, stages, intervals, and inconsistent waves',()=>{const q=[0,0,0,1]as const,p={position:[0,0,0]as[number,number,number],quaternion:q},op={stage:63,wave:1,start:.8,end:.9,pickup:p,clear:p,waypoint:p,approach:p,finalPose:p};expect(()=>createEiffelPhysicalConstructionClock([op],60,{hoistMetresPerSecond:0})).toThrow(/positive/);expect(()=>createEiffelPhysicalConstructionClock([op],60,{stages:[63.5]})).toThrow(/integers/);expect(()=>createEiffelPhysicalConstructionClock([{...op,end:.7}])).toThrow(/start < end/);expect(()=>createEiffelPhysicalConstructionClock([op,{...op,end:.91}])).toThrow(/inconsistent/);});
});
