import{readFileSync}from'node:fs';
import{Box3,BufferAttribute,DoubleSide,Mesh,Object3D,Raycaster,Vector3}from'three';
import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
import{describe,expect,it}from'vitest';

const folder='artifacts/eiffel-long-load-carrier-2026-09-08/';
const design=JSON.parse(readFileSync(folder+'carrier-design.json','utf8'))as{partId:string;payloadSize:[number,number,number];payloadBottom:number;headPlateTop:number;carrierTop:number;hookY:number;eyeCenters:[number,number,number][];eyeInnerRadius:number;slingRadius:number;productionReady:boolean};
const load=async(path=folder+'model/long-load-carrier.glb')=>{const bytes=readFileSync(path);return(await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;};
const dispose=(root:Object3D)=>root.traverse(o=>{if(o instanceof Mesh)o.geometry.dispose();});
const byRole=(root:Object3D,role:string)=>{let found:Mesh|undefined;root.traverse(o=>{if(o instanceof Mesh&&o.userData.wf_role===role)found=o;});if(!found)throw Error(`Missing ${role}`);return found;};
const vertices=(mesh:Mesh)=>{const a=mesh.geometry.getAttribute('position')as BufferAttribute,out:Vector3[]=[];for(let i=0;i<a.count;i++){const p=new Vector3(a.getX(i),a.getY(i),a.getZ(i)).applyMatrix4(mesh.matrixWorld);if(!out.some(q=>q.distanceTo(p)<1e-6))out.push(p);}return out;};
const enableDoubleSide=(mesh:Mesh)=>{for(const material of(Array.isArray(mesh.material)?mesh.material:[mesh.material]))material.side=DoubleSide;};

describe('Eiffel upright long-load carrier asset',()=>{
 it('preserves the real member and seats it on the actual bottom shoe',async()=>{const root=await load();try{root.updateMatrixWorld(true);const payload=byRole(root,'actual-payload'),shoe=byRole(root,'bottom-shoe');expect(payload.userData.wf_part_id).toBe(design.partId);const bounds=new Box3().setFromObject(payload),size=bounds.getSize(new Vector3());for(let i=0;i<3;i++)expect(Math.abs(size.getComponent(i)-design.payloadSize[i]!)).toBeLessThan(2e-5);expect(Math.abs(bounds.min.y-design.payloadBottom)).toBeLessThan(2e-5);
   enableDoubleSide(shoe);const bottom=vertices(payload).filter(p=>Math.abs(p.y-bounds.min.y)<1e-6);expect(bottom).toHaveLength(4);const ray=new Raycaster(),failures:string[]=[];for(const[i,p]of bottom.entries()){ray.set(p.clone().add(new Vector3(0,.04,0)),new Vector3(0,-1,0));const hit=ray.intersectObject(shoe,false).find(h=>h.point.y<=p.y+1e-5);if(!hit||Math.abs(hit.point.y-p.y)>2e-5)failures.push(`${i}:${hit?.point.y??'miss'}`);}expect(failures).toEqual([]);
  }finally{dispose(root);}},30_000);

 it('connects all four tension rods to actual shoe and head faces',async()=>{const root=await load();try{root.updateMatrixWorld(true);const shoe=byRole(root,'bottom-shoe'),head=byRole(root,'head-plate'),rods:Mesh[]=[];root.traverse(o=>{if(o instanceof Mesh&&String(o.userData.wf_role).startsWith('tension-rod-'))rods.push(o);});expect(rods).toHaveLength(4);enableDoubleSide(shoe);enableDoubleSide(head);const ray=new Raycaster(),failures:string[]=[];for(const rod of rods){const b=new Box3().setFromObject(rod),center=b.getCenter(new Vector3());if(Math.abs(b.min.y-design.payloadBottom)>2e-5)failures.push(`${rod.name}:bottom:${b.min.y}`);if(Math.abs(b.max.y-(design.headPlateTop-.06))>2e-5)failures.push(`${rod.name}:top:${b.max.y}`);ray.set(new Vector3(center.x,b.min.y+.04,center.z),new Vector3(0,-1,0));const low=ray.intersectObject(shoe,false).find(h=>h.point.y<=b.min.y+1e-5);if(!low||Math.abs(low.point.y-b.min.y)>2e-5)failures.push(`${rod.name}:shoe:${low?.point.y??'miss'}`);ray.set(new Vector3(center.x,b.max.y-.04,center.z),new Vector3(0,1,0));const high=ray.intersectObject(head,false).find(h=>h.point.y>=b.max.y-1e-5);if(!high||Math.abs(high.point.y-b.max.y)>2e-5)failures.push(`${rod.name}:head:${high?.point.y??'miss'}`);}expect(failures).toEqual([]);
  }finally{dispose(root);}},30_000);

 it('keeps both actual collar openings outside the square payload section',async()=>{const root=await load();try{root.updateMatrixWorld(true);const payload=new Box3().setFromObject(byRole(root,'actual-payload')),half=Math.max(Math.abs(payload.min.x),Math.abs(payload.max.x),Math.abs(payload.min.z),Math.abs(payload.max.z)),ray=new Raycaster(),failures:string[]=[];for(const role of['lateral-collar-1.25','lateral-collar-4.75']){const collar=byRole(root,role);enableDoubleSide(collar);const y=Number(role.split('-').at(-1));for(let i=0;i<32;i++){const angle=2*Math.PI*i/32,dir=new Vector3(Math.cos(angle),0,Math.sin(angle)),payloadEdge=half/Math.max(Math.abs(dir.x),Math.abs(dir.z));ray.set(new Vector3(0,y,0),dir);const hit=ray.intersectObject(collar,false)[0];if(!hit)failures.push(`${role}:${i}:no-inner-face`);else if(hit.distance<payloadEdge-2e-5)failures.push(`${role}:${i}:${hit.distance}<${payloadEdge}`);}}expect(failures).toEqual([]);
  }finally{dispose(root);}},30_000);

 it('provides four actual eye bores around the prescribed rope endpoints',async()=>{const root=await load();try{root.updateMatrixWorld(true);const head=byRole(root,'head-plate');enableDoubleSide(head);const ray=new Raycaster(),hook=new Vector3(0,design.hookY,0),failures:string[]=[];for(const[i,raw]of design.eyeCenters.entries()){const eye=new Vector3(...raw),towardHook=hook.clone().sub(eye).normalize(),contact=eye.clone().addScaledVector(towardHook,design.eyeInnerRadius-design.slingRadius),radial=new Vector3(eye.x,0,eye.z).normalize(),normal=new Vector3(-radial.z,0,radial.x);const contactOffset=contact.distanceTo(eye);if(Math.abs(contactOffset-(design.eyeInnerRadius-design.slingRadius))>2e-6)failures.push(`eye-${i}:endpoint:${contactOffset}`);ray.set(eye.clone(),towardHook);const inner=ray.intersectObject(head,false).find(h=>h.distance>1e-6&&h.distance<.12);if(!inner||Math.abs(inner.distance-design.eyeInnerRadius)>1e-4||inner.distance<=contactOffset)failures.push(`eye-${i}:inner-face:${inner?.distance??'miss'}`);for(const sign of[-1,1]){ray.set(contact.clone(),normal.clone().multiplyScalar(sign));const blocked=ray.intersectObject(head,false).find(h=>h.distance<.06);if(blocked)failures.push(`eye-${i}:bore-${sign}:${blocked.distance}`);}}expect(failures).toEqual([]);
  }finally{dispose(root);}},30_000);

 it('seats all four actual shoe corners on the actual first-floor cart bed',async()=>{const [carrier,bridge]=await Promise.all([load(),load('artifacts/eiffel-first-floor-transfer-2026-09-08/model/first-floor-bridge.glb')]);try{carrier.position.set(-21.5,57.94000244140625+.34,-4);carrier.updateMatrixWorld(true);bridge.updateMatrixWorld(true);const shoe=byRole(carrier,'bottom-shoe');let cart:Object3D|undefined,bed:Mesh|undefined;bridge.traverse(o=>{if(o.userData.wf_role==='stock-cart')cart=o;});expect(cart).toBeDefined();cart!.traverse(o=>{if(o instanceof Mesh&&o.name.replace(/\d+$/,'').startsWith('cart-bed'))bed=o;});expect(bed).toBeDefined();enableDoubleSide(bed!);const points=vertices(shoe),bottom=Math.min(...points.map(p=>p.y)),corners=points.filter(p=>Math.abs(p.y-bottom)<1e-6);expect(corners).toHaveLength(4);const ray=new Raycaster(),failures:string[]=[];for(const[i,p]of corners.entries()){ray.set(p.clone().add(new Vector3(0,.08,0)),new Vector3(0,-1,0));const hit=ray.intersectObject(bed!,false).find(h=>h.point.y<=p.y+1e-5);if(!hit||Math.abs(hit.point.y-p.y)>2e-5)failures.push(`${i}:${p.toArray()}:${hit?.point.y??'miss'}`);}expect(failures).toEqual([]);
  }finally{dispose(carrier);dispose(bridge);}},30_000);
});
