import { readFileSync } from 'node:fs';
import { DoubleSide, Matrix4, Mesh, Quaternion, Raycaster, Vector3, type Object3D } from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { describe, expect, it } from 'vitest';
import type { EiffelKitManifest } from '../src/data/eiffelKitTypes';
import { createEiffelProductionPlan, sampleEiffelProductionOperation } from '../src/engine/eiffelProductionConstruction';
import { EIFFEL_SUMMIT_RIGID_ASSEMBLIES } from '../src/engine/eiffelRigidAssembly';
import type { RigidPose } from '../src/engine/eiffelRigid';

const assetPath='artifacts/eiffel-summit-assembly-2026-09-08/model/summit-mast-assemblies.glb';
const kitPath='public/models/eiffel-construction-kit/tower-kit.glb';
const manifest=JSON.parse(readFileSync(kitPath.replace('.glb','.manifest.json'),'utf8'))as EiffelKitManifest;
const ids=[...new Set(EIFFEL_SUMMIT_RIGID_ASSEMBLIES.flatMap(link=>[link.parentPartId,link.childPartId]))];
const plan=createEiffelProductionPlan(manifest);
const poseMatrix=(pose:RigidPose)=>new Matrix4().compose(new Vector3(...pose.position),new Quaternion(...pose.quaternion),new Vector3(1,1,1));
async function load(path:string){const bytes=readFileSync(path);const root=(await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;root.updateMatrixWorld(true);return root;}
function meshes(root:Object3D){const result=new Map<string,Mesh>();root.traverse(object=>{if(object instanceof Mesh&&ids.includes(String(object.userData.wf_part))){const id=String(object.userData.wf_part);if(result.has(id))throw Error(`Duplicate ${id}`);result.set(id,object);}});return result;}
function corners(mesh:Mesh,matrix=mesh.matrixWorld){const position=mesh.geometry.getAttribute('position');return Array.from({length:position.count},(_,i)=>new Vector3().fromBufferAttribute(position,i).applyMatrix4(matrix));}
function triangleSignatures(mesh:Mesh,matrix=mesh.matrixWorld){const points=corners(mesh,matrix),index=mesh.geometry.index,count=index?.count??points.length,keys:string[]=[];for(let i=0;i<count;i+=3){const triangle=[0,1,2].map(j=>points[index?.getX(i+j)??i+j]!);keys.push([triangle[0]!.distanceTo(triangle[1]!),triangle[1]!.distanceTo(triangle[2]!),triangle[2]!.distanceTo(triangle[0]!)].sort((a,b)=>a-b).map(v=>v.toFixed(4)).join(','));}return keys.sort();}
function maxVertexDelta(a:readonly Vector3[],b:readonly Vector3[]){expect(a).toHaveLength(b.length);return Math.max(...a.map((point,i)=>point.distanceTo(b[i]!)));}
function dispose(root:Object3D){root.traverse(object=>{if(object instanceof Mesh){object.geometry.dispose();for(const material of Array.isArray(object.material)?object.material:[object.material])material.dispose();}});}

describe('actual summit mast preassemblies',()=>{
 it('preserves all seven current kit meshes and their triangle topology within 0.1 mm',async()=>{const[assembly,kit]=await Promise.all([load(assetPath),load(kitPath)]);try{const a=meshes(assembly),k=meshes(kit);expect([...a]).toHaveLength(7);for(const id of ids){const am=a.get(id)!,km=k.get(id)!;expect(am,`${id} assembly mesh`).toBeDefined();expect(km,`${id} kit mesh`).toBeDefined();expect(maxVertexDelta(corners(am),corners(km)),id).toBeLessThan(1e-4);expect(am.geometry.index?.count??am.geometry.getAttribute('position').count).toBe(km.geometry.index?.count??km.geometry.getAttribute('position').count);expect(triangleSignatures(am),`${id} topology`).toEqual(triangleSignatures(km));}}finally{dispose(assembly);dispose(kit);}},30_000);
 it('grounds the west receiver, carrier and compact crane pad on actual terrace triangles',async()=>{const root=await load(kitPath);try{const byStage=new Map(manifest.parts.map(part=>[part.id,part.stage])),surfaces:Mesh[]=[];root.traverse(object=>{if(object instanceof Mesh&&(byStage.get(String(object.userData.wf_part))??99)<=56){surfaces.push(object);for(const material of Array.isArray(object.material)?object.material:[object.material])material.side=DoubleSide;}});const op=plan.byPart.get('summit-crown-m072-c000')!,sample=sampleEiffelProductionOperation(op,op.start+(op.end-op.start)*.01),receiver=op.receiver!,pad=op.station!.supportPadSize!;expect(receiver.center[1]-receiver.size[1]/2).toBeCloseTo(op.station!.base[1],8);expect(sample.carrier!.center[1]-sample.carrier!.size[1]/2).toBeCloseTo(sample.carrier!.supportY,8);const footprints=[{center:receiver.center,size:receiver.size},{center:op.station!.base,size:pad}];for(const footprint of footprints)for(let ix=0;ix<=20;ix++)for(let iz=0;iz<=20;iz++){const x=footprint.center[0]+(ix/20-.5)*footprint.size[0],z=footprint.center[2]+(iz/20-.5)*footprint.size[2],hit=new Raycaster(new Vector3(x,282,z),new Vector3(0,-1,0),0,3).intersectObjects(surfaces,false)[0];expect(hit,`terrace support ${x},${z}`).toBeDefined();expect(hit!.point.y).toBeCloseTo(op.station!.base[1],4);}}finally{dispose(root);}},30_000);
 it('parents every child beneath its declared assembly owner',async()=>{const root=await load(assetPath);try{const found=meshes(root);for(const link of EIFFEL_SUMMIT_RIGID_ASSEMBLIES){const child=found.get(link.childPartId)!;expect(child.userData.wf_assembly_owner).toBe(link.parentPartId);expect(child.parent?.userData.wf_role).toBe('mast-assembly');expect(child.parent?.userData.wf_assembly_owner).toBe(link.parentPartId);expect(found.get(link.parentPartId)!.parent).toBe(child.parent);}}finally{dispose(root);}});
 it('reposes the Blender hierarchy by the same rigid delta as every runtime child sample',async()=>{const root=await load(assetPath);try{const found=meshes(root);for(const link of EIFFEL_SUMMIT_RIGID_ASSEMBLIES){const parent=plan.byPart.get(link.parentPartId)!,child=plan.byPart.get(link.childPartId)!;for(const u of[.13,.41,.73,.97]){const t=parent.start+(parent.end-parent.start)*u,parentPose=sampleEiffelProductionOperation(parent,t).pose,childPose=sampleEiffelProductionOperation(child,t).pose,parentDelta=poseMatrix(parentPose).multiply(poseMatrix(parent.part.finalPose).invert()),childDelta=poseMatrix(childPose).multiply(poseMatrix(child.part.finalPose).invert()),finalVertices=corners(found.get(link.childPartId)!);expect(maxVertexDelta(finalVertices.map(v=>v.clone().applyMatrix4(parentDelta)),finalVertices.map(v=>v.clone().applyMatrix4(childDelta))),`${link.childPartId}@${u}`).toBeLessThan(1e-6);}}}finally{dispose(root);}},30_000);
});
