import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {sampleEiffelJointRiggers,type EiffelJointRiggerWorker} from '../src/engine/eiffelJointRiggers';
import {sampleEiffelJointCampaign} from '../src/engine/eiffelJointCampaign';
import {eiffelTerrainHeightAt} from '../src/engine/eiffelTerrain';
import {EiffelOccupancy,eiffelAxisBox,eiffelBoxPenetration,eiffelSolidBox,type EiffelSolidBox} from '../src/engine/eiffelOccupancy';
import {eiffelReceiverBeamBox} from '../src/engine/eiffelUpperClearance';
import type {RigidVec3 as V} from '../src/engine/eiffelRigid';
import type {EiffelKitPart} from '../src/data/eiffelKitTypes';
import type {EiffelKitManifest} from '../src/data/eiffelKitTypes';
import {createEiffelProductionPlan} from '../src/engine/eiffelProductionConstruction';
import {invertRigidPose,rotateRigidVector,transformRigidPoint} from '../src/engine/eiffelRigid';
import frozen from '../artifacts/eiffel-joint-campaign-2026-09-07/campaign-routes.json';
import groundSupport from '../artifacts/eiffel-integration-2026-09-07/guyenet-ne-station.json';
import jointSupport from '../artifacts/eiffel-joint-campaign-2026-09-07/joint-support.json';
const distance=(a:V,b:V)=>Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);
const activeArm=(worker:EiffelJointRiggerWorker,index:number)=>index===0?worker.arms.left:worker.arms.right;
const cartBox=(s:ReturnType<typeof sampleEiffelJointCampaign>['carriers'][number])=>eiffelSolidBox({localBounds:{min:[-s.bedSize[0]/2,-s.bedSize[1]/2,-s.bedSize[2]/2],max:[s.bedSize[0]/2,s.bedSize[1]/2,s.bedSize[2]/2]}},{position:s.bedPose.position,quaternion:s.bedPose.quaternion});
const bodyBoxes=(worker:EiffelJointRiggerWorker)=>[eiffelReceiverBeamBox(worker.torso[0],worker.torso[1],.15),eiffelAxisBox(worker.head.center,[.24,.24,.24]),eiffelAxisBox([worker.hip[0],worker.hip[1]+.1,worker.hip[2]],[.24,.28,.26]),...([worker.leftLeg,worker.rightLeg].flatMap(leg=>[eiffelReceiverBeamBox(leg.start,leg.joint,.055),eiffelReceiverBeamBox(leg.joint,leg.end,.055)])),...([worker.arms.left,worker.arms.right].flatMap(arm=>[eiffelReceiverBeamBox(arm.shoulder,arm.elbow,.045),eiffelReceiverBeamBox(arm.elbow,arm.hand,.045)])),eiffelAxisBox(worker.leftFoot.center,worker.leftFoot.size),eiffelAxisBox(worker.rightFoot.center,worker.rightFoot.size)];

describe('Eiffel joint-campaign ground slingers',()=>{
 it('keeps one two-person team planted at the shared pickup for both loads',()=>{const anchor=sampleEiffelJointRiggers(0);for(const seconds of [0,10,14,30,64,65,78,82,100,135])sampleEiffelJointRiggers(seconds).workers.forEach((worker,index)=>{expect(worker.id).toBe(anchor.workers[index]!.id);expect(worker.leftFoot).toEqual(anchor.workers[index]!.leftFoot);expect(worker.rightFoot).toEqual(anchor.workers[index]!.rightFoot);for(const foot of [worker.leftFoot,worker.rightFoot])expect(foot.center[1]-foot.size[1]/2).toBeCloseTo(eiffelTerrainHeightAt(foot.center[0],foot.center[2]),10);});});
 it('uses human-scale IK and puts hands on each active load actual loose ends and basket eyes',()=>{for(const [base,load] of [[0,0],[68,1]] as const){for(const local of [13,13.25,13.5,13.9,13.999]){const seconds=base+local,crew=sampleEiffelJointRiggers(seconds),campaign=sampleEiffelJointCampaign(seconds);crew.workers.forEach((worker,index)=>{for(const arm of [worker.arms.left,worker.arms.right]){expect(distance(arm.shoulder,arm.elbow)).toBeCloseTo(.38,9);expect(distance(arm.elbow,arm.hand)).toBeCloseTo(.4,9);}expect(crew.activeLoadIndex).toBe(load);expect(worker.contact.kind).toBe('loose-sling-end');expect(distance(activeArm(worker,index).hand,campaign.rigging.slings[index]!.points[2])).toBeLessThan(1e-10);});}const seconds=base+14,crew=sampleEiffelJointRiggers(seconds),campaign=sampleEiffelJointCampaign(seconds),loops=campaign.basketLoops.filter(loop=>loop.loadIndex===load);expect(loops).toHaveLength(2);crew.workers.forEach((worker,index)=>{expect(worker.contact.kind).toBe('pickup-lug');expect(distance(activeArm(worker,index).hand,campaign.rigging.lugs[index]!)).toBeLessThan(1e-10);expect(distance(campaign.rigging.lugs[index]!,loops[index]!.points[0]!)).toBeLessThan(1e-10);});}});
 it('keeps rendered bodies and limbs clear of both oriented carts and cargo outside designated hand contact',()=>{for(let seconds=0;seconds<=135;seconds+=.05){const crew=sampleEiffelJointRiggers(seconds),campaign=sampleEiffelJointCampaign(seconds),carts=campaign.carriers.map(cartBox),loads=campaign.loads.map((load,index)=>eiffelSolidBox(frozen.loads[index]!.part as unknown as EiffelKitPart,load.pose));crew.workers.forEach((worker,index)=>{const bodies=[eiffelReceiverBeamBox(worker.torso[0],worker.torso[1],.15),eiffelAxisBox(worker.head.center,[.24,.24,.24]),eiffelAxisBox([worker.hip[0],worker.hip[1]+.1,worker.hip[2]],[.24,.28,.26]),...([worker.leftLeg,worker.rightLeg].flatMap(leg=>[eiffelReceiverBeamBox(leg.start,leg.joint,.055),eiffelReceiverBeamBox(leg.joint,leg.end,.055)])),eiffelAxisBox(worker.leftFoot.center,worker.leftFoot.size),eiffelAxisBox(worker.rightFoot.center,worker.rightFoot.size)];for(const [bodyIndex,body] of bodies.entries()){for(const [cartIndex,cart] of carts.entries())expect(eiffelBoxPenetration(body,cart),`${seconds}:worker${index}:body${bodyIndex}:cart${cartIndex}`).toBe(0);for(const [loadIndex,load] of loads.entries())expect(eiffelBoxPenetration(body,load),`${seconds}:worker${index}:body${bodyIndex}:load${loadIndex}`).toBe(0);}
      const idle=index===0?worker.arms.right:worker.arms.left;for(const segment of [[idle.shoulder,idle.elbow],[idle.elbow,idle.hand]] as const)for(const cart of carts)expect(eiffelBoxPenetration(eiffelReceiverBeamBox(segment[0],segment[1],.045),cart)).toBe(0);
    });}} ,15000);
 it('is continuous at both handoffs and deterministic under backward queries',()=>{for(const boundary of [12,13,14,14.6,80,81,82,82.6]){const a=sampleEiffelJointRiggers(boundary-1e-5),b=sampleEiffelJointRiggers(boundary+1e-5);a.workers.forEach((worker,index)=>expect(distance(activeArm(worker,index).hand,activeArm(b.workers[index]!,index).hand)).toBeLessThan(1e-3));}const a=sampleEiffelJointRiggers(82.3);sampleEiffelJointRiggers(12.7);expect(sampleEiffelJointRiggers(82.3)).toEqual(a);expect(()=>sampleEiffelJointRiggers(NaN)).toThrow(/finite/);});
 it('clears 1,900 completed tower solids and all 245 installed support members',()=>{const manifest=JSON.parse(readFileSync('public/models/eiffel-construction-kit/tower-kit.manifest.json','utf8')) as EiffelKitManifest,plan=createEiffelProductionPlan(manifest),occupancy=new EiffelOccupancy(manifest.parts.filter(part=>plan.byPart.get(part.id)!.end<=jointSupport.freeze).map(part=>({part,end:0})));const root={position:groundSupport.station.root as unknown as V,quaternion:[0,Math.sin(-Math.PI/8),0,Math.cos(-Math.PI/8)] as const},inverse=invertRigidPose(root),old=groundSupport.proposedStructure.map(member=>{const local=eiffelReceiverBeamBox(transformRigidPoint(inverse,member.a as unknown as V),transformRigidPoint(inverse,member.b as unknown as V),member.halfWidth),box:EiffelSolidBox={center:transformRigidPoint(root,local.center),half:local.half,axes:local.axes.map(axis=>rotateRigidVector(root.quaternion,axis)) as unknown as EiffelSolidBox['axes']};return box;}),added=[...jointSupport.beams.map(member=>eiffelReceiverBeamBox(member.a as unknown as V,member.b as unknown as V,member.halfWidth)),...jointSupport.boxes.map(box=>eiffelAxisBox(box.center as unknown as V,box.size as unknown as V))],supports=[...old,...added],times=new Set([0,10,14.8,40,65,78,82.8,100,135]);for(let t=10;t<=14.8;t+=.05)times.add(t);for(let t=78;t<=82.8;t+=.05)times.add(t);expect(occupancy.byPart.size).toBe(1900);expect(supports).toHaveLength(245);for(const seconds of times)for(const worker of sampleEiffelJointRiggers(seconds).workers)for(const body of bodyBoxes(worker)){expect(occupancy.penetration(body,0),`${seconds}:${worker.id}:tower`).toBe(0);for(const [index,support] of supports.entries()){if(Math.abs(body.center[0]-support.center[0])>8||Math.abs(body.center[1]-support.center[1])>8||Math.abs(body.center[2]-support.center[2])>8)continue;expect(eiffelBoxPenetration(body,support),`${seconds}:${worker.id}:support${index}`).toBe(0);}}},30_000);
});
