import {describe,expect,it} from'vitest';
import manifest from'../public/models/eiffel-construction-kit/tower-kit.manifest.json';
import{EIFFEL_SUMMIT_CARGO_DURATION,eiffelSummitCargoRoleTransforms,sampleEiffelSummitCargo}from'../src/engine/eiffelSummitCargo';
import{composeRigidPoses,invertRigidPose}from'../src/engine/eiffelRigid';
import type{RigidPose}from'../src/engine/eiffelRigid';
const by=new Map(manifest.parts.map(p=>[p.id,p]));
const dist=(a:readonly number[],b:readonly number[])=>Math.hypot(...a.map((x,i)=>x-b[i]!));
describe('summit cargo candidate',()=>{
 it('uses a fixed tail pivot for a one-axis upend and releases only under tackle hold',()=>{for(const assembly of[1,2]as const){for(let i=0;i<=280;i++){const s=sampleEiffelSummitCargo(8+i/10,assembly);expect(dist(s.tailCollarWorld,s.tailPivotWorld)).toBeLessThan(2e-9);expect(s.tailEngagement).toBe(1);}expect(sampleEiffelSummitCargo(44,assembly).tailEngagement).toBe(0);}});
 it('keeps every child rigidly attached and finishes at exact manifest poses',()=>{for(const assembly of[1,2]as const){const samples=[0,8,22,36,44,47,50,63,76,82,88,94,101,109,112];for(const t of samples){const s=sampleEiffelSummitCargo(t,assembly),parent=by.get(s.members[0]!.partId)!;for(const child of s.members.slice(1)){const expected=composeRigidPoses(s.parentPose,composeRigidPoses(invertRigidPose(parent.finalPose as unknown as RigidPose),by.get(child.partId)!.finalPose as unknown as RigidPose));expect(dist(child.pose.position,expected.position)).toBeLessThan(1e-9);expect(dist(child.pose.quaternion,expected.quaternion)).toBeLessThan(1e-9);}}for(const m of sampleEiffelSummitCargo(112,assembly).members){expect(dist(m.pose.position,by.get(m.partId)!.finalPose.position)).toBeLessThan(2e-5);}}});
 it('stays inside the six metre upper-collar reach and has continuous reversible samples',()=>{for(const assembly of[1,2]as const){let prior=sampleEiffelSummitCargo(0,assembly);for(let i=1;i<=EIFFEL_SUMMIT_CARGO_DURATION*20;i++){const t=i/20,s=sampleEiffelSummitCargo(t,assembly),r=Math.hypot(s.upperCollarWorld[0]+.9,s.upperCollarWorld[2]);expect(r).toBeLessThanOrEqual(Math.sqrt((s.jib.heelOffset+s.jib.boomLength)**2+s.jib.blockSideOffset**2));expect(r).toBeGreaterThanOrEqual(s.jib.blockSideOffset);expect(dist(s.parentPose.position,prior.parentPose.position)).toBeLessThan(.25);prior=s;}for(const t of[0,8,36,44,50,76,88,101,112])expect(sampleEiffelSummitCargo(t,assembly)).toEqual(sampleEiffelSummitCargo(t,assembly));}});
 it('publishes only authored rigid roles and labels cable topology pending',()=>{const s=sampleEiffelSummitCargo(60,1),roles=eiffelSummitCargoRoleTransforms(s);expect(new Set(roles.map(r=>r.role)).size).toBe(roles.length);expect(s.bridle.fixedLegLength).toBeCloseTo(Math.hypot(.14,1.61),12);expect(s.bridle.lowerBlockCenter[1]-s.upperCollarWorld[1]).toBeCloseTo(1.8,12);expect(s.cable.pending).toBe(true);expect(s.cable.rope.lowerBlockEye).toEqual(s.bridle.lowerEye);expect(s.cable.rope.bridle).toHaveLength(2);});
});
