import {readFileSync} from 'node:fs';
import {Mesh,Raycaster,Vector3} from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {describe,expect,it} from 'vitest';
import type {EiffelKitManifest} from '../src/data/eiffelKitTypes';
import {eiffelConvexBox,eiffelConvexPenetration,eiffelConvexSolid,eiffelConvexTranslationSweep,type EiffelConvexSolid} from '../src/engine/eiffelConvex';
import {eiffelSolidBox} from '../src/engine/eiffelOccupancy';
import type {RigidVec3 as V} from '../src/engine/eiffelRigid';

type Prism={id:string;role:string;vertices:V[]};
type Bridge={floorY:number;deckY:number;shapes:Prism[];productionReady:boolean};
const bridge=JSON.parse(readFileSync('artifacts/eiffel-second-floor-supply-2026-09-08/bridge-design.json','utf8')) as Bridge;
const platform=JSON.parse(readFileSync('artifacts/eiffel-relay-platform-2026-09-08/platform-occupancy.json','utf8')) as Prism[];
const winch=JSON.parse(readFileSync('artifacts/eiffel-relay-winch-2026-09-08/design.json','utf8')) as {frame:Prism[]};
const manifest=JSON.parse(readFileSync('public/models/eiffel-construction-kit/tower-kit.manifest.json','utf8')) as EiffelKitManifest;
const faces=[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]] as const;
const bridgeSolids=bridge.shapes.map(prism=>({id:prism.id,kind:'bridge',solid:eiffelConvexSolid(prism.vertices,faces)}));
const platformSolids=platform.map(prism=>({id:prism.id,kind:'platform197',solid:eiffelConvexSolid(prism.vertices,faces)}));
const winchSolids=winch.frame.map(prism=>({id:prism.id,kind:'winch',solid:eiffelConvexSolid(prism.vertices,faces)}));
const kit=manifest.parts.filter(part=>part.stage<=45).map(part=>({id:part.id,kind:'kit',solid:eiffelConvexBox(eiffelSolidBox(part,part.finalPose))}));
const overlaps=(a:EiffelConvexSolid,b:EiffelConvexSolid)=>!a.min.some((v,k)=>v>b.max[k]!||a.max[k]!<b.min[k]!);
const collisions=(moving:EiffelConvexSolid,obstacles:{id:string;kind:string;solid:EiffelConvexSolid}[])=>obstacles.flatMap(obstacle=>{if(!overlaps(moving,obstacle.solid))return[];const depth=eiffelConvexPenetration(moving,obstacle.solid);return depth>1e-6?[`${obstacle.kind}:${obstacle.id}:${depth}`]:[];});
const crate=(center:V)=>eiffelConvexBox({center,half:[.3,.9,.3],axes:[[1,0,0],[0,1,0],[0,0,1]]});
const sweep=(start:V,end:V)=>eiffelConvexTranslationSweep(crate(start),[end[0]-start[0],end[1]-start[1],end[2]-start[2]]);
async function towerMeshes(){const bytes=readFileSync('public/models/eiffel-construction-kit/tower-kit.glb');const scene=(await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;scene.updateMatrixWorld(true);const stage=new Map(manifest.parts.map(part=>[part.id,part.stage])),meshes:Mesh[]=[];scene.traverse(o=>{if(o instanceof Mesh&&stage.get(String(o.userData.wf_part))===34)meshes.push(o);});return{scene,meshes};}

describe('Eiffel second-floor freight supply geometry',()=>{
 it('keeps all 211 bridge prisms clear of every completed kit envelope through stage 45',()=>{expect(bridge.productionReady).toBe(false);expect(bridge.shapes).toHaveLength(211);const failures:string[]=[];for(const member of bridgeSolids)failures.push(...collisions(member.solid,kit));expect(failures).toEqual([]);},30_000);
 it('seats all four bearing bottom corners on the actual second-floor deck',async()=>{const{scene,meshes}=await towerMeshes();try{const bearings=bridge.shapes.filter(shape=>shape.id.startsWith('bearing-'));expect(bearings).toHaveLength(4);const ray=new Raycaster(),failures:string[]=[];for(const bearing of bearings){const bottom=Math.min(...bearing.vertices.map(v=>v[1])),corners=bearing.vertices.filter(v=>Math.abs(v[1]-bottom)<1e-9);expect(corners,bearing.id).toHaveLength(4);for(const [index,corner]of corners.entries()){ray.set(new Vector3(corner[0],bottom+.5,corner[2]),new Vector3(0,-1,0));const hit=ray.intersectObjects(meshes,false)[0];if(!hit||Math.abs(hit.point.y-bridge.floorY)>2e-5||Math.abs(hit.point.y-bottom)>2e-5)failures.push(`${bearing.id}:${index}:${hit?.point.y??'miss'}`);}}expect(failures).toEqual([]);}finally{scene.traverse(o=>{if(o instanceof Mesh)o.geometry.dispose();});}},30_000);
 it('keeps the source cart wheel tracks supported by actual floor or flush bridge planks',async()=>{const{scene,meshes}=await towerMeshes();try{const ray=new Raycaster(),misses:string[]=[];for(let centerX=-15;centerX<=0.0001;centerX+=.25)for(const dx of[-.25,.25])for(const dz of[-.38,.38]){const x=centerX+dx,z=-1.8+dz;if(x>=-9){expect(z).toBeGreaterThanOrEqual(-2.4);expect(z).toBeLessThanOrEqual(-1.2);continue;}ray.set(new Vector3(x,116.64,z),new Vector3(0,-1,0));const hit=ray.intersectObjects(meshes,false).find(candidate=>Math.abs(candidate.point.y-bridge.floorY)<2e-5);if(!hit)misses.push(`${x},${z}`);}expect(misses).toEqual([]);expect(bridge.deckY).toBeCloseTo(bridge.floorY,5);}finally{scene.traverse(o=>{if(o instanceof Mesh)o.geometry.dispose();});}},30_000);
 it('has no internal wood or iron penetration and preserves the authored bearing stack',()=>{const failures:string[]=[];for(let i=0;i<bridgeSolids.length;i++)for(let j=i+1;j<bridgeSolids.length;j++){const a=bridgeSolids[i]!,b=bridgeSolids[j]!;if(bridge.shapes[i]!.role===bridge.shapes[j]!.role||!overlaps(a.solid,b.solid))continue;const depth=eiffelConvexPenetration(a.solid,b.solid);if(depth>1e-7)failures.push(`${a.id}:${b.id}:${depth}`);}expect(failures).toEqual([]);const ledgers=bridge.shapes.filter(s=>s.id.startsWith('ledger-')),joists=bridge.shapes.filter(s=>s.id.startsWith('cross-joist-')),planks=bridge.shapes.filter(s=>s.id.startsWith('plank-'));expect(ledgers).toHaveLength(2);expect(joists).toHaveLength(23);expect(planks).toHaveLength(90);const extent=(shape:Prism,k:number,which:'min'|'max')=>Math[which](...shape.vertices.map(v=>v[k]!));for(const plank of planks){expect(extent(plank,1,'min'),plank.id).toBeCloseTo(extent(ledgers[0]!,1,'max'),10);for(const ledger of ledgers)expect(Math.min(extent(plank,2,'max'),extent(ledger,2,'max'))-Math.max(extent(plank,2,'min'),extent(ledger,2,'min')),`${plank.id}:${ledger.id}`).toBeGreaterThan(0);}for(const joist of joists){for(const ledger of ledgers){expect(extent(joist,1,'max'),`${joist.id}:${ledger.id}`).toBeCloseTo(extent(ledger,1,'min'),10);expect(Math.min(extent(joist,0,'max'),extent(ledger,0,'max'))-Math.max(extent(joist,0,'min'),extent(ledger,0,'min'))).toBeGreaterThan(0);}}});
 it('clears the crate transfer and continuous central ascent to the 197m receiver',()=>{const obstacles=[...bridgeSolids,...kit,...platformSolids,...winchSolids];const legs:[string,V,V][]=[['bridge-transfer',[-15,117.38,-1.8],[0,117.38,-1.8]],['relay-ascent',[0,117.38,-1.8],[0,198.1,-1.8]]];const failures=legs.flatMap(([name,start,end])=>collisions(sweep(start,end),obstacles).map(hit=>`${name}:${hit}`));expect(failures).toEqual([]);},30_000);
});
