import{it,expect}from'vitest';import{eiffelSummitWorkerRig}from'../src/engine/eiffelSummitWorker';import{sampleEiffelSummitOutboardAccess,sampleEiffelSummitOutboardCrankWorker}from'../src/engine/eiffelSummitOutboardWorker';
it('keeps rigid limb reach and three contacts throughout the outboard handoff candidate',()=>{for(let i=0;i<=8000;i++){const s=sampleEiffelSummitOutboardAccess(i/100);expect(()=>eiffelSummitWorkerRig(s.targets)).not.toThrow();expect(s.contacts.length).toBeGreaterThanOrEqual(3);}for(let i=0;i<=720;i++)expect(()=>eiffelSummitWorkerRig(sampleEiffelSummitOutboardCrankWorker(i*Math.PI/360))).not.toThrow();});
it('joins the candidate crank and reverses independent of query history',()=>{expect(sampleEiffelSummitOutboardAccess(80).targets).toEqual(sampleEiffelSummitOutboardCrankWorker(0));const a=sampleEiffelSummitOutboardAccess(69);sampleEiffelSummitOutboardAccess(80);expect(sampleEiffelSummitOutboardAccess(69)).toEqual(a);});
it('keeps exact forearm-to-wrist lengths for the upper endpoint',async()=>{const{sampleEiffelSummitOutboardEndpoint}=await import('../src/engine/eiffelSummitOutboardWorker');for(let i=0;i<=72;i++){const r=eiffelSummitWorkerRig(sampleEiffelSummitOutboardEndpoint(i*Math.PI/36));for(let j=0;j<2;j++){expect(Math.hypot(...r.elbows[j]!.map((v,k)=>v-r.wrists[j]![k]!))).toBeCloseTo(.31,10);expect(Math.hypot(...r.shoulders[j]!.map((v,k)=>v-r.elbows[j]![k]!))).toBeCloseTo(.31,10);}}});
it('contacts the actual outboard grabrail and crank grip with source palms',async()=>{
 const{EiffelSummitGinPoleSystem}=await import('../src/render/three/EiffelSummitGinPoleSystem');const{sampleEiffelSummitOutboardEndpoint}=await import('../src/engine/eiffelSummitOutboardWorker');const{Mesh,Raycaster,Vector3,DoubleSide}=await import('three');const system=new EiffelSummitGinPoleSystem('/artifacts/eiffel-summit-cargo-2026-09-08/model/summit-cargo-rig.glb');await system.ready;
 const palms:any[]=[],grips:any[]=[],rails:any[]=[];system.group.traverse(o=>{if(o instanceof Mesh){for(const m of Array.isArray(o.material)?o.material:[o.material])m.side=DoubleSide;if(o.name.startsWith('pusher_hand-'))palms.push(o);if(o.name.startsWith('extended-climb-control-grip'))grips.push(o);if(o.name.startsWith('outboard-worker-grabrail'))rails.push(o);}});expect(grips).toHaveLength(1);expect(rails).toHaveLength(1);const ray=new Raycaster();
 for(let i=0;i<=72;i++){const a=i*Math.PI/36;system.updateOutboardEndpoint(a);const s=sampleEiffelSummitOutboardEndpoint(a);const left=s.hands[0],right=s.hands[1];ray.set(new Vector3(...left),new Vector3(-1,0,0));const palm=ray.intersectObjects(palms,false)[0];ray.set(new Vector3(.6,left[1],left[2]),new Vector3(-1,0,0));const rail=ray.intersectObjects(rails,false)[0];expect(palm).toBeDefined();expect(rail).toBeDefined();expect(palm!.point.x).toBeLessThanOrEqual(rail!.point.x+.00005);
 ray.set(new Vector3(...right),new Vector3(0,0,1));const hand=ray.intersectObjects(palms,false)[0];ray.set(new Vector3(right[0],right[1],right[2]-.1),new Vector3(0,0,1));const grip=ray.intersectObjects(grips,false)[0];expect(hand).toBeDefined();expect(grip).toBeDefined();expect(hand!.point.z).toBeGreaterThanOrEqual(grip!.point.z-.00005);}
 system.dispose();
});
