import{it,expect}from'vitest';
import{sampleEiffelSummitOperationAccess}from'../src/engine/eiffelSummitOperationAccess';
import{sampleEiffelSummitOutboardEndpoint}from'../src/engine/eiffelSummitOutboardWorker';
import{eiffelSummitWorkerRig,eiffelSummitWorkerRoles}from'../src/engine/eiffelSummitWorker';
it('retains three fixed limb contacts and exact connected lengths in the access candidate',()=>{for(let i=0;i<=1600;i++){const s=sampleEiffelSummitOperationAccess(i/20),r=eiffelSummitWorkerRig(s.targets);if(i>0){const old=eiffelSummitWorkerRoles(sampleEiffelSummitOperationAccess((i-1)/20).targets),next=eiffelSummitWorkerRoles(s.targets);for(let k=0;k<old.length;k++)expect(Math.hypot(...old[k]!.position.map((v,j)=>v-next[k]!.position[j]!))).toBeLessThan(.05);}expect(s.contacts.length).toBeGreaterThanOrEqual(3);for(let j=0;j<2;j++){expect(Math.hypot(...r.wrists[j]!.map((v,k)=>v-r.elbows[j]![k]!))).toBeCloseTo(.31,9);expect(Math.hypot(...r.elbows[j]!.map((v,k)=>v-r.shoulders[j]![k]!))).toBeCloseTo(.31,9);expect(Math.hypot(...r.knees[j]!.map((v,k)=>v-r.ankles[j]![k]!))).toBeCloseTo(.43,9);expect(Math.hypot(...r.hips[j]!.map((v,k)=>v-r.knees[j]![k]!))).toBeCloseTo(.44,9);}}});
it('ends at the admitted endpoint and reverses without query state',()=>{const a=sampleEiffelSummitOperationAccess(73);sampleEiffelSummitOperationAccess(80);expect(sampleEiffelSummitOperationAccess(73)).toEqual(a);const end=eiffelSummitWorkerRoles(sampleEiffelSummitOperationAccess(80).targets),expected=eiffelSummitWorkerRoles(sampleEiffelSummitOutboardEndpoint(0));for(let i=0;i<end.length;i++)for(let k=0;k<3;k++)expect(end[i]!.position[k]).toBeCloseTo(expected[i]!.position[k]!,10);});
it('keeps released-hand phases anchored to the two unchanged soles and the other palm',()=>{const a=sampleEiffelSummitOperationAccess(64).targets,b=sampleEiffelSummitOperationAccess(68).targets;for(let t=64;t<80;t+=.125){const s=sampleEiffelSummitOperationAccess(t);expect(s.targets.feet).toEqual(a.feet);if(t<68)expect(s.targets.hands[1]).toEqual(a.hands[1]);else expect(s.targets.hands[0]).toEqual(b.hands[0]);}});
it('keeps all rigid body parts continuous at limb and transfer boundaries',()=>{for(const t of[...Array.from({length:64},(_,i)=>i+1),54,60,68,80]){const a=eiffelSummitWorkerRoles(sampleEiffelSummitOperationAccess(t-1e-6).targets),b=eiffelSummitWorkerRoles(sampleEiffelSummitOperationAccess(t+1e-6).targets);for(let i=0;i<a.length;i++){expect(Math.hypot(...a[i]!.position.map((v,k)=>v-b[i]!.position[k]!))).toBeLessThan(1e-5);expect(Math.abs(a[i]!.quaternion.reduce((sum,v,k)=>sum+v*b[i]!.quaternion[k]!,0))).toBeGreaterThan(1-1e-7);}}});
it('puts each declared contact on actual source ladder, grabrail or stopped crank surfaces',async()=>{
 const{EiffelSummitGinPoleSystem}=await import('../src/render/three/EiffelSummitGinPoleSystem');const{Mesh,Raycaster,Vector3,DoubleSide}=await import('three');const system=new EiffelSummitGinPoleSystem('/artifacts/eiffel-summit-operation-2026-09-08/model/summit-operation-rig.glb');await system.ready;
 const rungs:any[]=[],palms:any[]=[],rail:any[]=[],grip:any[]=[];system.group.traverse(o=>{if(o instanceof Mesh){for(const m of Array.isArray(o.material)?o.material:[o.material])m.side=DoubleSide;if(o.name.startsWith('ladder-rung'))rungs.push(o);if(o.name.startsWith('pusher_hand-'))palms.push(o);if(o.name.startsWith('outboard-worker-grabrail'))rail.push(o);if(o.name.startsWith('extended-climb-control-grip'))grip.push(o);}});const ray=new Raycaster();
 for(let t=0;t<=80;t+=.5){const s=sampleEiffelSummitOperationAccess(t);system.updateAccess(0);for(const r of eiffelSummitWorkerRoles(s.targets))system.group.traverse(o=>{if(o.userData.wf_role===`pusher-${r.role}`){o.position.set(...r.position);o.quaternion.set(...r.quaternion);}});system.group.updateMatrixWorld(true);
 for(let j=0;j<2;j++){
  if(s.contacts.includes('foot-'+j)){const p=s.targets.feet[j]!;ray.set(new Vector3(p[0],p[1]+.05,p[2]+.1),new Vector3(0,-1,0));const hit=ray.intersectObjects(rungs,false)[0];expect(hit).toBeDefined();expect(hit!.point.y).toBeCloseTo(p[1],4);}
  if(!s.contacts.includes('hand-'+j))continue;const p=s.targets.hands[j]!;
  if(j===0&&t>=68){ray.set(new Vector3(...p),new Vector3(-1,0,0));const hand=ray.intersectObjects(palms,false)[0];ray.set(new Vector3(.6,p[1],p[2]),new Vector3(-1,0,0));const hit=ray.intersectObjects(rail,false)[0];expect(hand).toBeDefined();expect(hit).toBeDefined();expect(hand!.point.x).toBeLessThanOrEqual(hit!.point.x+.00005);}
  else{ray.set(new Vector3(...p),new Vector3(0,0,1));const hand=ray.intersectObjects(palms,false)[0];ray.set(new Vector3(p[0],p[1],p[2]-.1),new Vector3(0,0,1));const hit=ray.intersectObjects(j===1&&t===80?grip:rungs,false)[0];expect(hand).toBeDefined();expect(hit).toBeDefined();expect(hand!.point.z).toBeGreaterThanOrEqual(hit!.point.z-.00005);}
 }
 }system.dispose();
});
it('updates actual GPU batch poses while fixed hardware stays fixed and disposes once',async()=>{
 const{EiffelSummitGinPoleSystem}=await import('../src/render/three/EiffelSummitGinPoleSystem');const{Mesh,Matrix4}=await import('three');const s=new EiffelSummitGinPoleSystem('/artifacts/eiffel-summit-operation-2026-09-08/model/summit-operation-rig.glb');await s.ready;s.updateOperationAccess(0);
 const roles=new Map<string,any>();s.group.traverse(o=>{if(o.userData.wf_role)roles.set(o.userData.wf_role,o);});const fixed=['guide-0-fixed','guide-3-fixed','cargo-drive-fixed','climb-drive-fixed'].map(id=>({id,matrix:roles.get(id).matrixWorld.toArray()}));const batches=(s as any).batches as {mesh:any;sources:{mesh:any;id:number}[]}[];
 for(const t of[0,54,64,66,68,72,76,80,0]){s.updateOperationAccess(t);const expected=eiffelSummitWorkerRoles(sampleEiffelSummitOperationAccess(t).targets);for(const r of expected)expect(roles.get('pusher-'+r.role).position.toArray()).toEqual(r.position);for(const f of fixed)expect(roles.get(f.id).matrixWorld.toArray()).toEqual(f.matrix);for(const b of batches)for(const entry of b.sources){const actual=new Matrix4();b.mesh.getMatrixAt(entry.id,actual);for(let i=0;i<16;i++)expect(actual.elements[i]).toBeCloseTo(entry.mesh.matrixWorld.elements[i],4);}}
 const geometries=new Set<any>();s.group.traverse(o=>{if(o instanceof Mesh)geometries.add(o.geometry);});const counts=new Map<any,number>();for(const g of geometries)g.addEventListener('dispose',()=>counts.set(g,(counts.get(g)??0)+1));s.dispose();s.dispose();for(const g of geometries)expect(counts.get(g)).toBe(1);
});
