import{readFileSync}from'node:fs';import{Box3,DoubleSide,Mesh,Object3D,Raycaster,Vector3}from'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{describe,expect,it}from'vitest';type V=[number,number,number];type Eye={center:V;axis:V;points:V[]};type Strand={eye:Eye;line:[V,V];carrierEye:Eye;carrierHoleCenter:V};type D={ropeRadius:number;upperEye:Eye;strands:Strand[];productionReady:boolean};
const folder='artifacts/eiffel-closed-sling-2026-09-08/',d=JSON.parse(readFileSync(folder+'design.json','utf8'))as D,carrier=JSON.parse(readFileSync('artifacts/eiffel-long-load-carrier-2026-09-08/carrier-design.json','utf8'))as{hookY:number;eyeInnerRadius:number},mix=(a:V,b:V,t:number):V=>a.map((v,i)=>v+(b[i]!-v)*t)as V,sub=(a:V,b:V):V=>a.map((v,i)=>v-b[i]!)as V,dot=(a:V,b:V)=>a.reduce((s,v,i)=>s+v*b[i]!,0);
const paths=[{id:'upper-rope-eye',points:d.upperEye.points},...d.strands.flatMap((s,i)=>[{id:`lower-rope-eye-${i}`,points:s.eye.points},{id:`sling-leg-${i}`,points:s.line},{id:`carrier-rope-eye-${i}`,points:s.carrierEye.points}])];
function segDist(p1:V,q1:V,p2:V,q2:V){const u=sub(q1,p1),v=sub(q2,p2),w=sub(p1,p2),a=dot(u,u),b=dot(u,v),c=dot(v,v),dd=dot(u,w),e=dot(v,w),den=a*c-b*b;let s=den<1e-15?0:(b*e-c*dd)/den;s=Math.max(0,Math.min(1,s));let t=Math.max(0,Math.min(1,c?(b*s+e)/c:0));s=Math.max(0,Math.min(1,a?(b*t-dd)/a:0));return Math.hypot(...sub(mix(p1,q1,s),mix(p2,q2,t)));}
const load=async(path:string)=>{const bytes=readFileSync(path);return(await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;},dispose=(root:Object3D)=>root.traverse(o=>{if(o instanceof Mesh)o.geometry.dispose();});

describe('Eiffel closed lower sling asset',()=>{
 it('exports all 14 roles and every authored path endpoint',async()=>{const root=await load(folder+'model/closed-sling.glb');try{root.updateMatrixWorld(true);const roles=new Map<string,Mesh>();root.traverse(o=>{if(o instanceof Mesh)roles.set(String(o.userData.wf_role),o);});const expected=['master-link','upper-rope-eye',...d.strands.flatMap((_,i)=>[`lower-rope-eye-${i}`,`sling-leg-${i}`,`carrier-rope-eye-${i}`])];expect(roles.size).toBe(14);expect([...roles.keys()].sort()).toEqual(expected.sort());const failures:string[]=[];for(const path of paths){const box=new Box3().setFromObject(roles.get(path.id)!).expandByScalar(2e-5);for(const[i,p]of path.points.entries())if(!box.containsPoint(new Vector3(...p)))failures.push(`${path.id}:${i}`);}expect(failures).toEqual([]);}finally{dispose(root);}},30_000);

 it('wraps each rectangular top bar once and passes through the actual carrier-eye bore',async()=>{const [sling,head]=await Promise.all([load(folder+'model/closed-sling.glb'),load('artifacts/eiffel-long-load-carrier-2026-09-08/model/long-load-carrier.glb')]);try{sling.updateMatrixWorld(true);head.position.y=-carrier.hookY;head.updateMatrixWorld(true);let headPlate:Mesh|undefined;head.traverse(o=>{if(o instanceof Mesh&&o.userData.wf_role==='head-plate')headPlate=o;});expect(headPlate).toBeDefined();for(const material of(Array.isArray(headPlate!.material)?headPlate!.material:[headPlate!.material]))material.side=DoubleSide;const ray=new Raycaster(),failures:string[]=[];for(const[i,s]of d.strands.entries()){const axis=s.carrierEye.axis,tangent:V=[-axis[2],0,axis[0]],angles:number[]=[];let barDistance=Infinity,holeDistance=Infinity;for(let k=0;k<s.carrierEye.points.length-1;k++)for(let j=0;j<=200;j++){const p=mix(s.carrierEye.points[k]!,s.carrierEye.points[k+1]!,j/200),q=sub(p,s.carrierEye.center),distance=Math.hypot(Math.max(0,Math.abs(q[1])-.012),Math.max(0,Math.abs(dot(q,tangent))-.009),Math.abs(dot(q,axis)));barDistance=Math.min(barDistance,distance);holeDistance=Math.min(holeDistance,Math.hypot(...sub(p,s.carrierHoleCenter)));}for(const p of s.carrierEye.points){const q=sub(p,s.carrierEye.center);angles.push(Math.atan2(dot(q,tangent),q[1]));}let winding=0;for(let k=1;k<angles.length;k++)winding+=((angles[k]!-angles[k-1]!+Math.PI)%(2*Math.PI)+2*Math.PI)%(2*Math.PI)-Math.PI;if(barDistance<d.ropeRadius-1e-10)failures.push(`${i}:bar:${barDistance}`);if(holeDistance+d.ropeRadius>carrier.eyeInnerRadius+1e-10)failures.push(`${i}:bore:${holeDistance}`);if(Math.abs(winding-2*Math.PI)>1e-10)failures.push(`${i}:winding:${winding}`);const radial=new Vector3(s.carrierHoleCenter[0],0,s.carrierHoleCenter[2]).normalize(),boreAxis=new Vector3(-radial.z,0,radial.x);for(const sign of[-1,1]){ray.set(new Vector3(...s.carrierHoleCenter),boreAxis.clone().multiplyScalar(sign));const blocked=ray.intersectObject(headPlate!,false).find(h=>h.distance<.06);if(blocked)failures.push(`${i}:actual-bore-${sign}:${blocked.distance}`);}}expect(failures).toEqual([]);}finally{dispose(sling);dispose(head);}},30_000);

 it('keeps all 70 non-splice path pairs mutually clear',()=>{const failures:string[]=[];let excluded=0,pairs=0,minimum=Infinity;const index=(id:string,prefix:string)=>id.startsWith(prefix)?Number(id.slice(prefix.length)):undefined;for(let i=0;i<paths.length;i++)for(let j=i+1;j<paths.length;j++){const a=paths[i]!,b=paths[j]!,la=index(a.id,'lower-rope-eye-'),lb=index(b.id,'lower-rope-eye-'),sa=index(a.id,'sling-leg-'),sb=index(b.id,'sling-leg-'),ca=index(a.id,'carrier-rope-eye-'),cb=index(b.id,'carrier-rope-eye-'),splice=(la!==undefined&&sb===la)||(lb!==undefined&&sa===lb)||(sa!==undefined&&cb===sa)||(sb!==undefined&&ca===sb);if(splice){excluded++;continue;}pairs++;let distance=Infinity;for(let x=0;x<a.points.length-1;x++)for(let y=0;y<b.points.length-1;y++)distance=Math.min(distance,segDist(a.points[x]!,a.points[x+1]!,b.points[y]!,b.points[y+1]!));minimum=Math.min(minimum,distance);if(distance<2*d.ropeRadius-1e-12)failures.push(`${a.id}:${b.id}:${distance}`);}expect(excluded).toBe(8);expect(pairs).toBe(70);expect(minimum).toBeCloseTo(.07113021857668303,12);expect(failures).toEqual([]);expect(d.productionReady).toBe(false);});
});
