import{describe,expect,it}from'vitest';
import{readFileSync}from'node:fs';
import type{EiffelKitManifest}from'../src/data/eiffelKitTypes';
import{createEiffelProductionPlan,sampleEiffelProductionOperation}from'../src/engine/eiffelProductionConstruction';
import{EIFFEL_SUMMIT_RIGID_ASSEMBLIES,eiffelRigidAssemblyChildPose,eiffelRigidAssemblyRelativePose}from'../src/engine/eiffelRigidAssembly';
import{composeRigidPoses,invertRigidPose,transformRigidPoint}from'../src/engine/eiffelRigid';

const manifest=JSON.parse(readFileSync('public/models/eiffel-construction-kit/tower-kit.manifest.json','utf8'))as EiffelKitManifest;
const plan=createEiffelProductionPlan(manifest);
const near=(a:readonly number[],b:readonly number[],digits=10)=>a.forEach((value,index)=>expect(value).toBeCloseTo(b[index]!,digits));

describe('Eiffel summit factory rigid assemblies',()=>{
 it('derives both exact child frames from immutable final poses',()=>{expect(EIFFEL_SUMMIT_RIGID_ASSEMBLIES).toHaveLength(4);for(const link of EIFFEL_SUMMIT_RIGID_ASSEMBLIES){const child=plan.byPart.get(link.childPartId)!,parent=plan.byPart.get(link.parentPartId)!,relative=eiffelRigidAssemblyRelativePose(parent.part.finalPose,child.part.finalPose);expect(child.assemblyParentId).toBe(parent.part.id);expect(child.assemblyRelativePose).toEqual(relative);expect(child.assemblyParentOperation).toBe(parent);expect(eiffelRigidAssemblyChildPose(parent.part.finalPose,relative)).toEqual(composeRigidPoses(parent.part.finalPose,relative));near(eiffelRigidAssemblyChildPose(parent.part.finalPose,relative).position,child.part.finalPose.position);near(eiffelRigidAssemblyChildPose(parent.part.finalPose,relative).quaternion,child.part.finalPose.quaternion);}});
 it('keeps every child corner in one rigid parent frame through dense forward and reverse queries',()=>{for(const link of EIFFEL_SUMMIT_RIGID_ASSEMBLIES){const child=plan.byPart.get(link.childPartId)!,parent=plan.byPart.get(link.parentPartId)!,relative=child.assemblyRelativePose!;for(const fraction of[0,...Array.from({length:101},(_,i)=>(i+.5)/101),1]){const t=parent.start+(parent.end-parent.start)*fraction,ps=sampleEiffelProductionOperation(parent,t),cs=sampleEiffelProductionOperation(child,t);expect(cs.phase).toBe(ps.phase);const expected=ps.phase==='seated'?child.part.finalPose:eiffelRigidAssemblyChildPose(ps.pose,relative);near(cs.pose.position,expected.position);near(cs.pose.quaternion,expected.quaternion);for(const x of[child.part.localBounds.min[0],child.part.localBounds.max[0]])for(const y of[child.part.localBounds.min[1],child.part.localBounds.max[1]])for(const z of[child.part.localBounds.min[2],child.part.localBounds.max[2]])near(transformRigidPoint(cs.pose,[x,y,z]),transformRigidPoint(expected,[x,y,z]));}sampleEiffelProductionOperation(child,parent.start);const again=sampleEiffelProductionOperation(child,parent.start+(parent.end-parent.start)*.63);const parentAgain=sampleEiffelProductionOperation(parent,parent.start+(parent.end-parent.start)*.63);near(composeRigidPoses(invertRigidPose(parentAgain.pose),again.pose).position,relative.position);}});
 it('inherits owner timing and creates exactly one equipment job per assembly',()=>{for(const link of EIFFEL_SUMMIT_RIGID_ASSEMBLIES){const child=plan.byPart.get(link.childPartId)!,parent=plan.byPart.get(link.parentPartId)!;expect({start:child.start,end:child.end,wave:child.wave,hero:child.hero}).toEqual({start:parent.start,end:parent.end,wave:parent.wave,hero:parent.hero});const t=(parent.start+parent.end)/2,parentSample=sampleEiffelProductionOperation(parent,t),childSample=sampleEiffelProductionOperation(child,t);expect(parentSample.crane).not.toBeNull();expect(childSample).toMatchObject({crane:null,bracket:null,carrier:null,receiver:null});const active=plan.operations.filter(op=>op.start<=t&&op.end>t).map(op=>sampleEiffelProductionOperation(op,t));expect(active.filter(sample=>sample.crane).length).toBeLessThanOrEqual(active.length-1);}});
 it('preserves the external operation array and byPart identity invariant',()=>{expect(plan.operations).toHaveLength(manifest.parts.length);expect(plan.byPart.size).toBe(manifest.parts.length);for(const operation of plan.operations)expect(plan.byPart.get(operation.part.id)).toBe(operation);});
});
