import {describe,it,expect} from 'vitest';import {readFileSync} from 'node:fs';
import type {EiffelKitManifest} from '../src/data/eiffelKitTypes';import {planEiffelSummitStock,EIFFEL_SUMMIT_STOCK_FLOOR} from '../src/engine/eiffelSummitStock';import {transformedRigidBounds} from '../src/engine/eiffelRigid';
// This envelope-only stock study records the preserved pre-revision summit.
const manifest=JSON.parse(readFileSync('artifacts/eiffel-summit-revision-2026-09-08/before-kit/tower-kit.manifest.json','utf8')) as EiffelKitManifest,parts=new Map(manifest.parts.map(p=>[p.id,p]));
describe('archived pre-revision Eiffel summit stock packing study',()=>{
 it('packs every stage 61-63 identity deterministically into the sixteen shelves',()=>{const a=planEiffelSummitStock(manifest),b=planEiffelSummitStock(manifest),expected=manifest.parts.filter(p=>p.stage>=61&&p.stage<=63).map(p=>p.id).sort();expect(a).toEqual(b);expect(a.productionReady).toBe(false);expect(a.envelopeOnly).toBe(true);expect(a.racks).toHaveLength(8);expect(a.placements).toHaveLength(247);expect(a.placements.map(p=>p.partId).sort()).toEqual(expected);expect(new Set(a.placements.map(p=>p.partId)).size).toBe(247);expect(Math.max(...a.placements.map(p=>p.binIndex))).toBeLessThan(16);});
 it('keeps independently transformed bounds on their shelf, inside each rack and separated by 0.08m',()=>{const plan=planEiffelSummitStock(manifest),racks=new Map(plan.racks.map(r=>[r.id,r])),world=plan.placements.map(placement=>{const part=parts.get(placement.partId)!,rack=racks.get(placement.rackId)!,bounds=transformedRigidBounds(placement.pose,part.localBounds.min,part.localBounds.max),shelf=rack.shelfTops[placement.shelfIndex];expect(bounds.min[1]).toBeCloseTo(shelf,10);expect(placement.bin.x).toBeGreaterThanOrEqual(0);expect(placement.bin.z).toBeGreaterThanOrEqual(0);expect(placement.bin.x+placement.bin.width).toBeLessThanOrEqual(rack.usableLength+1e-9);expect(placement.bin.z+placement.bin.depth).toBeLessThanOrEqual(rack.usableDepth+1e-9);expect(bounds.max[0]-bounds.min[0]).toBeCloseTo(rack.yaw?part.transportSize[2]:part.transportSize[0],7);return{placement,bounds};});
  for(let i=0;i<world.length;i++)for(let j=i+1;j<world.length;j++){const a=world[i]!,b=world[j]!;if(a.placement.shelfIndex!==b.placement.shelfIndex)continue;const dx=Math.max(0,Math.max(a.bounds.min[0],b.bounds.min[0])-Math.min(a.bounds.max[0],b.bounds.max[0])),dz=Math.max(0,Math.max(a.bounds.min[2],b.bounds.min[2])-Math.min(a.bounds.max[2],b.bounds.max[2]));expect(Math.max(dx,dz),`${a.placement.partId}/${b.placement.partId}`).toBeGreaterThanOrEqual(.08-1e-7);}
 });
 it('uses fixed terrace-floor foot references for every physical rack',()=>{const plan=planEiffelSummitStock(manifest);for(const rack of plan.racks){expect(rack.feet).toHaveLength(4);expect(new Set(rack.feet.map(f=>f.id)).size).toBe(4);for(const foot of rack.feet){expect(foot.support).toBe('summit-terrace-floor');expect(foot.position[1]).toBe(EIFFEL_SUMMIT_STOCK_FLOOR);expect(Number.isFinite(foot.position[0]+foot.position[2])).toBe(true);}}});
});
