import{afterEach,describe,expect,it}from'vitest';import{InstancedMesh,Object3D,Vector3}from'three';import{sampleEiffelLongLoadFilm}from'../src/engine/eiffelLongLoadFilm';import{assertEiffelSecondFloorRelaySample,type EiffelSecondFloorRelaySample}from'../src/engine/eiffelSecondFloorRelay';import{EiffelLongLoadFilmSystem}from'../src/render/three/EiffelLongLoadFilmSystem';
const systems:EiffelLongLoadFilmSystem[]=[];const role=(root:Object3D,id:string)=>{let found:Object3D|undefined;root.traverse(o=>{if(o.userData.wf_role===id)found=o});if(!found)throw Error(`missing ${id}`);return found};
afterEach(()=>systems.splice(0).forEach(s=>s.dispose()));
function fixture():EiffelSecondFloorRelaySample{const end=sampleEiffelLongLoadFilm(280),add=(p:readonly number[])=>[p[0]!,p[1]!+1,p[2]!]as[number,number,number];return{seconds:0,phase:'take-tension',partId:'summit-access-stair-m000-c000',ownsPayload:true,seated:false,carrierPose:{position:add(end.carrierOrigin),quaternion:[0,0,0,1]},payloadPose:{position:add(end.carrierOrigin),quaternion:[0,0,0,1]},masterLinkPose:{position:add(end.masterOrigin),quaternion:[0,0,0,1]},retainedFirstHoistRope:end.worldRope,secondHoist:{worldRope:end.worldRope.map(add),attached:true,driveAdmitted:false},hardwareRoles:[],carrierSupport:'tackle',slingSupport:'tackle',cartPose:{position:[-8.5,116.14,-4],quaternion:[0,0,0,1]},cartSupport:'second-floor',cartAttached:false,fastening:{installed:0,required:4,released:true}}}
describe('second-floor relay renderer ownership hook',()=>{
 it('rejects duplicate/seated identity and invalid rope inputs',()=>{const valid=fixture();expect(()=>assertEiffelSecondFloorRelaySample(valid)).not.toThrow();expect(()=>assertEiffelSecondFloorRelaySample({...valid,seated:true}as unknown as EiffelSecondFloorRelaySample)).toThrow(/unseated stair identity/);expect(()=>assertEiffelSecondFloorRelaySample({...valid,secondHoist:{...valid.secondHoist,worldRope:[valid.secondHoist.worldRope[0]!]}})).toThrow(/retained and active rope/)});
 it('moves the existing payload owner without loading or seating another stair',async()=>{const system=new EiffelLongLoadFilmSystem();systems.push(system);await system.ready;system.update(280);const payload=role(system.group,'actual-payload'),uuid=payload.uuid,sourceCount=system.group.userData.sourceMeshCount,relay=fixture();system.updateRelay(relay);expect(role(system.group,'actual-payload').uuid).toBe(uuid);expect(system.group.userData.sourceMeshCount).toBe(sourceCount);expect(system.group.userData.partId).toBe(relay.partId);expect(system.group.userData.ownsPayload).toBe(true);expect(system.group.userData.seated).toBe(false);expect(system.group.userData.relay.carrierSupport).toBe('tackle');const rope=system.group.getObjectByName('long-load-hoist-rope')as InstancedMesh;expect(rope.count).toBe(sampleEiffelLongLoadFilm(280).worldRope.length-1);const relayRope=system.group.getObjectByName('second-floor-relay-rope')as InstancedMesh;expect(relayRope.count).toBe(relay.secondHoist.worldRope.length-1);expect(role(system.group,'stock-cart').getWorldPosition(new Vector3()).distanceTo(new Vector3(...relay.cartPose!.position))).toBeLessThan(1e-5);});
 it('clears the independent relay line and diagnostics on reverse seek',async()=>{const system=new EiffelLongLoadFilmSystem();systems.push(system);await system.ready;const relay=fixture();system.updateRelay(relay);expect((system.group.getObjectByName('second-floor-relay-rope')as InstancedMesh).count).toBeGreaterThan(0);system.update(280);expect((system.group.getObjectByName('second-floor-relay-rope')as InstancedMesh).count).toBe(0);expect(system.group.userData.relay).toBeNull();expect(system.group.userData.seconds).toBe(280);expect(system.group.userData.seated).toBe(false);});
});
