import {readFileSync} from 'node:fs';
import {BufferAttribute,Mesh,Object3D,Raycaster,Vector3} from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {describe,expect,it} from 'vitest';
import type {EiffelKitManifest} from '../src/data/eiffelKitTypes';
import {eiffelConvexBox,eiffelConvexPenetration,eiffelConvexSolid,eiffelConvexTranslationSweep,type EiffelConvexSolid} from '../src/engine/eiffelConvex';
import {eiffelSolidBox} from '../src/engine/eiffelOccupancy';
import {eiffelDiagonalRigAt,EIFFEL_DIAGONAL_LENGTH as L} from '../src/engine/eiffelDiagonalRig';
import type {RigidVec3 as V} from '../src/engine/eiffelRigid';

type Prism={id:string;vertices:V[]};const folder='artifacts/eiffel-diagonal-winch-2026-09-08/';
const design=JSON.parse(readFileSync(folder+'design.json','utf8')) as {productionReady:boolean;shapes:Prism[];direction:[number,number];lateral:[number,number]};
const receiver=JSON.parse(readFileSync('artifacts/eiffel-diagonal-receiver-2026-09-08/design.json','utf8')) as {shapes:Prism[]};
const first=JSON.parse(readFileSync('artifacts/eiffel-first-floor-transfer-2026-09-08/bridge-design.json','utf8')) as {shapes:Prism[]},second=JSON.parse(readFileSync('artifacts/eiffel-second-floor-supply-2026-09-08/bridge-design.json','utf8')) as {shapes:Prism[]};
const manifest=JSON.parse(readFileSync('public/models/eiffel-construction-kit/tower-kit.manifest.json','utf8')) as EiffelKitManifest,faces=[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]] as const,[dx,dz]=design.direction,[nx,nz]=design.lateral;
const shape=(p:Prism)=>eiffelConvexSolid(p.vertices,faces),environment=[...manifest.parts.filter(p=>p.stage<=45).map(p=>({id:p.id,solid:eiffelConvexBox(eiffelSolidBox(p,p.finalPose))})),...first.shapes.map(p=>({id:`first:${p.id}`,solid:shape(p)})),...second.shapes.map(p=>({id:`second:${p.id}`,solid:shape(p)})),...receiver.shapes.map(p=>({id:`receiver:${p.id}`,solid:shape(p)}))];
const overlaps=(a:EiffelConvexSolid,b:EiffelConvexSolid)=>!a.min.some((v,k)=>v>b.max[k]!||a.max[k]!<b.min[k]!);const hits=(s:EiffelConvexSolid,o:{id:string;solid:EiffelConvexSolid}[])=>o.flatMap(x=>{if(!overlaps(s,x.solid))return[];let d=eiffelConvexPenetration(s,x.solid);return d>1e-6?[`${x.id}:${d}`]:[]});
const load=async(path:string)=>{let b=readFileSync(path);return(await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')).scene},dispose=(o:Object3D)=>o.traverse(x=>{if(x instanceof Mesh)x.geometry.dispose();});
const vertices=(mesh:Mesh)=>{const a=mesh.geometry.getAttribute('position') as BufferAttribute,out:V[]=[];for(let i=0;i<a.count;i++){let p=new Vector3(a.getX(i),a.getY(i),a.getZ(i)).applyMatrix4(mesh.matrixWorld),v:V=[p.x,p.y,p.z];if(!out.some(q=>Math.hypot(q[0]-v[0],q[1]-v[1],q[2]-v[2])<1e-6))out.push(v);}return out;};
const obb=(mesh:Mesh)=>{const ps=vertices(mesh),vals=ps.map(p=>({u:p[0]*dx+p[2]*dz,y:p[1],n:p[0]*nx+p[2]*nz})),range=(k:'u'|'y'|'n')=>[Math.min(...vals.map(v=>v[k])),Math.max(...vals.map(v=>v[k]))],u=range('u'),y=range('y'),n=range('n'),cu=(u[0]+u[1])/2,cn=(n[0]+n[1])/2;return eiffelConvexBox({center:[cu*dx+cn*nx,(y[0]+y[1])/2,cu*dz+cn*nz],half:[(u[1]-u[0])/2,(y[1]-y[0])/2,(n[1]-n[0])/2],axes:[[dx,0,dz],[0,1,0],[nx,0,nz]]});};

describe('Eiffel diagonal fixed winch asset',()=>{
 it('matches all eight source boxes and preserves actual floor and rear-head bearings',async()=>{const [asset,tower,receiverAsset]=await Promise.all([load(folder+'model/diagonal-winch.glb'),load('public/models/eiffel-construction-kit/tower-kit.glb'),load('artifacts/eiffel-diagonal-receiver-2026-09-08/model/diagonal-receiver-frame.glb')]);try{asset.updateMatrixWorld(true);tower.updateMatrixWorld(true);receiverAsset.updateMatrixWorld(true);const sourceMeshes=new Map<string,Mesh>();asset.traverse(o=>{if(o instanceof Mesh&&o.userData.wf_source_id)sourceMeshes.set(String(o.userData.wf_source_id),o);});expect(sourceMeshes.size).toBe(8);const failures:string[]=[];for(const p of design.shapes){const mesh=sourceMeshes.get(p.id)!;const actual=vertices(mesh);expect(actual.length,p.id).toBeGreaterThanOrEqual(8);for(const corner of p.vertices){let distance=Math.min(...actual.map(v=>Math.hypot(v[0]-corner[0],v[1]-corner[1],v[2]-corner[2])));if(distance>2e-5)failures.push(`${p.id}:corner:${distance}`);}}const stages=new Map(manifest.parts.map(p=>[p.id,p.stage])),floors:Mesh[]=[];tower.traverse(o=>{if(o instanceof Mesh&&(stages.get(String(o.userData.wf_part))??99)<=34)floors.push(o);});const bed=sourceMeshes.get('winch-bed')!,ray=new Raycaster(),bedPoints=vertices(bed),bottom=Math.min(...bedPoints.map(v=>v[1]));for(const [i,p]of bedPoints.filter(v=>Math.abs(v[1]-bottom)<1e-6).entries()){ray.set(new Vector3(p[0],p[1]+.2,p[2]),new Vector3(0,-1,0));const hit=ray.intersectObjects(floors,false).find(h=>h.point.y<=p[1]+1e-5);if(!hit||Math.abs(hit.point.y-p[1])>2e-5)failures.push(`bed:${i}:${hit?.point.y??'miss'}`);}let rear:Mesh|undefined;receiverAsset.traverse(o=>{if(o instanceof Mesh&&o.userData.wf_source_id==='portal-head-1')rear=o;});expect(rear).toBeDefined();const rearPoints=vertices(rear!),rearTop=Math.max(...rearPoints.map(v=>v[1])),ranges=[[dx,dz],[nx,nz]].map(([x,z])=>[Math.min(...rearPoints.map(v=>v[0]*x!+v[2]*z!)),Math.max(...rearPoints.map(v=>v[0]*x!+v[2]*z!))]);for(const id of['guide-riser-0.6','guide-riser0.6']){const ps=vertices(sourceMeshes.get(id)!),y=Math.min(...ps.map(v=>v[1]));for(const p of ps.filter(v=>Math.abs(v[1]-y)<1e-6)){const q=[p[0]*dx+p[2]*dz,p[0]*nx+p[2]*nz];if(Math.abs(y-rearTop)>2e-5||q.some((v,i)=>v<ranges[i]![0]-2e-5||v>ranges[i]![1]+2e-5))failures.push(`${id}:bearing:${p}`);}}expect(failures).toEqual([]);}finally{dispose(asset);dispose(tower);dispose(receiverAsset);}},30_000);

 it('keeps non-source hardware clear of the environment and rope clear of fixed hardware',async()=>{const asset=await load(folder+'model/diagonal-winch.glb');try{asset.updateMatrixWorld(true);const hardware:Mesh[]=[];asset.traverse(o=>{if(o instanceof Mesh&&!o.userData.wf_source_id)hardware.push(o);});expect(hardware).toHaveLength(10);const failures=hardware.flatMap(mesh=>hits(obb(mesh),environment).map(hit=>`${mesh.name}:${hit}`));const ropeObstacles=hardware.filter(mesh=>!['guide-groove','drum-core'].includes(String(mesh.userData.wf_part))).map(mesh=>({id:mesh.name,solid:obb(mesh)}));for(const [u,y]of[[0,59.18000244140625],[0,118.7],[L/2,118.7],[L,118.7],[L,117.38]] as [number,number][]){const rope=eiffelDiagonalRigAt(u,y).rope;for(let i=1;i<rope.length;i++){const a=rope[i-1]!,b=rope[i]!,s=eiffelConvexTranslationSweep(eiffelConvexBox({center:a,half:[.008,.008,.008],axes:[[1,0,0],[0,1,0],[0,0,1]]}),[b[0]-a[0],b[1]-a[1],b[2]-a[2]]);failures.push(...hits(s,ropeObstacles).map(hit=>`rope:${u}:${i}:${hit}`));}}expect(failures).toEqual([]);}finally{dispose(asset);}},30_000);

 it('sweeps the shifted actual trolley from u .25 through L+.25 clear of the full environment',async()=>{const [trolley,winch]=await Promise.all([load('artifacts/eiffel-diagonal-trolley-2026-09-08/model/diagonal-trolley.glb'),load(folder+'model/diagonal-winch.glb')]);try{trolley.position.x+=dx*.25;trolley.position.z+=dz*.25;trolley.updateMatrixWorld(true);winch.updateMatrixWorld(true);const meshes:Mesh[]=[],winchMeshes:Mesh[]=[];trolley.traverse(o=>{if(o instanceof Mesh)meshes.push(o);});winch.traverse(o=>{if(o instanceof Mesh)winchMeshes.push(o);});expect(meshes).toHaveLength(17);const obstacles=[...environment,...winchMeshes.map(m=>({id:`winch:${m.name}`,solid:obb(m)}))],failures:string[]=[];for(const mesh of meshes){const swept=eiffelConvexTranslationSweep(obb(mesh),[dx*L,0,dz*L]);for(const obstacle of obstacles){if(!overlaps(swept,obstacle.solid))continue;const depth=eiffelConvexPenetration(swept,obstacle.solid),rolling=mesh.userData.wf_part==='trolley-wheel'&&obstacle.id.startsWith('receiver:rail-');if(depth>(rolling?2e-5:1e-6))failures.push(`${mesh.name}:${obstacle.id}:${depth}`);}}expect(failures).toEqual([]);}finally{dispose(trolley);dispose(winch);}},30_000);
});
