import { BatchedMesh, Box3, BufferAttribute, BufferGeometry, CylinderGeometry, LineBasicMaterial, LineSegments, Group, InstancedMesh, Matrix4, Mesh, MeshStandardMaterial, Object3D, Quaternion, Vector3, type Material } from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { eiffelSummitCargoRoleTransforms, sampleEiffelSummitCargo, type EiffelSummitCargoAssemblyIndex } from '../../engine/eiffelSummitCargo';
import { sampleEiffelSummitOperation } from '../../engine/eiffelSummitOperation';

/** Opt-in cargo candidate. It is intentionally absent from EiffelWorld/main film. */
export class EiffelSummitCargoRig {
  readonly group=new Group(); readonly ready:Promise<void>;
  private roles=new Map<string,Object3D>(); private parts=new Map<string,Object3D>(); private partBases=new Map<string,Matrix4>(); private readonly movingPartIds=new Set(['summit-crown-m072-c001','summit-crown-m074-c000','summit-crown-m075-c000','summit-crown-m072-c002','summit-crown-m076-c000']); private contextPartIds=new Set<string>(); private batches:{mesh:BatchedMesh;sources:{mesh:Mesh;id:number}[]}[]=[];private inverse=new Matrix4();private matrix=new Matrix4();private finals=new Map<string,{pose:any;matrix:Matrix4}>();private rope?:InstancedMesh;private ropeCenterline?:LineSegments;private windingRope?:InstancedMesh;private ropeGeometry?:CylinderGeometry;private ropeMaterial?:MeshStandardMaterial; private disposed=false; private seconds=0; private assembly:EiffelSummitCargoAssemblyIndex=1;
  constructor(private readonly assetUrl='/artifacts/eiffel-summit-cargo-2026-09-08/model/summit-cargo-rig.glb'){
    this.group.name='eiffel-summit-cargo-candidate';this.group.visible=false;this.ready=this.load().catch(error=>{this.dispose();throw error});
  }
  private async load(){let bytes:ArrayBuffer;try{const r=await fetch(this.assetUrl);if(!r.ok)throw Error('Missing summit cargo candidate');bytes=await r.arrayBuffer();}catch(error){if(typeof process==='undefined'||!process.versions?.node)throw error;const{readFileSync}=await import('node:fs');const b=readFileSync(this.assetUrl.startsWith('/')?this.assetUrl.slice(1):this.assetUrl);bytes=b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);}
    const asset=(await new GLTFLoader().parseAsync(bytes,'')).scene;
    let kitBytes:ArrayBuffer;try{const r=await fetch('/models/eiffel-construction-kit/tower-kit.glb');if(!r.ok)throw Error('Missing tower kit payload source');kitBytes=await r.arrayBuffer();}catch(error){if(typeof process==='undefined'||!process.versions?.node)throw error;const{readFileSync}=await import('node:fs');const b=readFileSync('public/models/eiffel-construction-kit/tower-kit.glb');kitBytes=b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);}
    const kit=(await new GLTFLoader().parseAsync(kitBytes,'')).scene,selected:Object3D[]=[];kit.updateMatrixWorld(true);kit.traverse(o=>{const id=String(o.userData.wf_part??'');if(!id)return;const box=new Box3().setFromObject(o),context=!this.movingPartIds.has(id)&&box.max.y>=279.8&&box.min.y<303&&(/^(summit-terrace-|summit-apartment-|summit-access-stair)/.test(id)||id==='summit-crown-m072-c000'||id==='summit-crown-m073-c000');if(this.movingPartIds.has(id)||context){selected.push(o);if(context)this.contextPartIds.add(id)}});for(const o of selected){asset.add(o);const id=String(o.userData.wf_part);if(this.movingPartIds.has(id))this.partBases.set(id,o.matrix.clone())}for(const assembly of[1,2]as const)for(const member of sampleEiffelSummitCargo(112,assembly).members)this.finals.set(member.partId,{pose:member.pose,matrix:new Matrix4().compose(new Vector3(...member.pose.position),new Quaternion(...member.pose.quaternion),new Vector3(1,1,1))});const retainedG=new Set<any>(),retainedM=new Set<any>();for(const o of selected)o.traverse(c=>{if(c instanceof Mesh){retainedG.add(c.geometry);for(const m of Array.isArray(c.material)?c.material:[c.material])retainedM.add(m)}});kit.traverse(o=>{if(o instanceof Mesh){if(!retainedG.has(o.geometry))o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])if(!retainedM.has(m))m.dispose()}});
    asset.traverse(o=>{if(o.userData.wf_role)this.roles.set(String(o.userData.wf_role),o);if(o.userData.wf_part&&!this.parts.has(String(o.userData.wf_part)))this.parts.set(String(o.userData.wf_part),o);});
    for(const id of['moving-pole','cargo-jib-yaw','cargo-jib-pitch','terrace-cargo-cart','cargo-tail-pin'])if(!this.roles.has(id))throw Error(`Missing summit cargo role ${id}`);
    if(this.disposed){asset.traverse(o=>{const m=o as unknown as{geometry?:{dispose():void}};m.geometry?.dispose()});return;}this.group.add(asset);this.ropeGeometry=new CylinderGeometry(.006,.006,1,8);this.ropeMaterial=new MeshStandardMaterial({color:0x6d5942,roughness:1});this.rope=new InstancedMesh(this.ropeGeometry,this.ropeMaterial,512);this.rope.name='summit-cargo-visible-rope';this.rope.frustumCulled=false;this.group.add(this.rope);const lineGeometry=new BufferGeometry();lineGeometry.setAttribute('position',new BufferAttribute(new Float32Array(512*6),3));lineGeometry.setDrawRange(0,0);this.ropeCenterline=new LineSegments(lineGeometry,new LineBasicMaterial({color:0x6d5942,transparent:true,opacity:.68,depthWrite:false}));this.ropeCenterline.name='summit-cargo-rope-distance-lines';this.ropeCenterline.frustumCulled=false;this.group.add(this.ropeCenterline);this.windingRope=new InstancedMesh(this.ropeGeometry,this.ropeMaterial,12000);this.windingRope.name='summit-cargo-visible-winding';this.windingRope.frustumCulled=false;this.group.add(this.windingRope);const cohorts=new Map<string,{material:Material;meshes:Mesh[]}>();asset.traverse(o=>{if(!(o instanceof Mesh))return;const materials=Array.isArray(o.material)?o.material:[o.material];if(materials.length!==1)throw Error('Summit cargo export must use one material per mesh');const material=materials[0]!,key=`${material.uuid}:${Object.keys(o.geometry.attributes).sort().join(',')}:${!!o.geometry.index}`,cohort=cohorts.get(key)??{material,meshes:[] as Mesh[]};cohort.meshes.push(o);cohorts.set(key,cohort)});for(const{material,meshes}of cohorts.values()){const vertices=meshes.reduce((n,m)=>n+m.geometry.attributes.position!.count,0),indices=meshes.reduce((n,m)=>n+(m.geometry.index?.count??0),0),batch=new BatchedMesh(meshes.length,vertices,indices,material);batch.name=`summit-cargo-batch-${this.batches.length}`;batch.frustumCulled=false;batch.perObjectFrustumCulled=true;const sources=meshes.map(mesh=>{const id=batch.addInstance(batch.addGeometry(mesh.geometry));mesh.visible=false;return{mesh,id}});this.group.add(batch);this.batches.push({mesh:batch,sources})}this.update(this.seconds,this.assembly);
  }
  private setVisibleRope(points:readonly(readonly[number,number,number])[],bridle:readonly{start:readonly[number,number,number];end:readonly[number,number,number]}[],extra:readonly(readonly(readonly[number,number,number])[])[]=[]){if(!this.rope)return;const paths=[points,...extra],segments=[...paths.flatMap(path=>path.slice(1).map((end,index)=>[path[index]!,end]as const)),...bridle.map(line=>[line.start,line.end]as const)];if(segments.length>512)throw Error('Summit cargo rope exceeds instance capacity');this.rope.count=segments.length;segments.forEach(([a,b],index)=>{const va=new Vector3(...a),vb=new Vector3(...b),delta=vb.clone().sub(va),q=new Quaternion().setFromUnitVectors(new Vector3(0,1,0),delta.clone().normalize());this.rope!.setMatrixAt(index,new Matrix4().compose(va.add(vb).multiplyScalar(.5),q,new Vector3(1,delta.length(),1)))});this.rope.instanceMatrix.needsUpdate=true;if(this.ropeCenterline){const attribute=this.ropeCenterline.geometry.getAttribute('position') as BufferAttribute;let count=0;for(const[a,b]of segments){if(Math.hypot(b[0]-a[0],b[1]-a[1],b[2]-a[2])<.4)continue;attribute.setXYZ(count++,...a);attribute.setXYZ(count++,...b);}attribute.needsUpdate=true;this.ropeCenterline.geometry.setDrawRange(0,count);}}
  private setWindingRope(points:readonly(readonly[number,number,number])[]){if(!this.windingRope)return;if(points.length-1>12000)throw Error('Summit cargo winding exceeds instance capacity');this.windingRope.count=Math.max(0,points.length-1);for(let index=0;index<points.length-1;index++){const va=new Vector3(...points[index]!),vb=new Vector3(...points[index+1]!),delta=vb.clone().sub(va),q=new Quaternion().setFromUnitVectors(new Vector3(0,1,0),delta.clone().normalize());this.windingRope.setMatrixAt(index,new Matrix4().compose(va.add(vb).multiplyScalar(.5),q,new Vector3(1,delta.length(),1)))}this.windingRope.instanceMatrix.needsUpdate=true;}
  private refreshBatches(active:Set<string>,hidden:Set<string>){this.group.updateMatrixWorld(true);this.inverse.copy(this.group.matrixWorld).invert();for(const batch of this.batches)for(const source of batch.sources){let enabled=true,cursor:Object3D|null=source.mesh;while(cursor){const role=String(cursor.userData.wf_role??''),part=String(cursor.userData.wf_part??'');if(hidden.has(role)||(part&&this.movingPartIds.has(part)&&!active.has(part)))enabled=false;cursor=cursor.parent;}batch.mesh.setVisibleAt(source.id,enabled);batch.mesh.setMatrixAt(source.id,this.matrix.multiplyMatrices(this.inverse,source.mesh.matrixWorld));}}
  updateOperation(seconds:number){const operation=sampleEiffelSummitOperation(seconds);if(operation.cargo){this.update(operation.cargo.seconds,operation.cargo.assembly);this.group.userData.seconds=operation.seconds;this.group.userData.operation=operation;return;}if(!operation.parkedCargo){this.update(112,2);this.group.userData.seconds=operation.seconds;this.group.userData.operation=operation;return;}this.update(112,1);for(const t of operation.activeRoleTransforms){const o=this.roles.get(t.role);if(!o)continue;if(t.position)o.position.set(...t.position);if(t.quaternion)o.quaternion.set(...t.quaternion);}const pc=operation.parkedCargo,wr=pc.rope.winding.drumRotation,wc=pc.rope.winding.drumCenter,rawWinding=pc.rope.winding.localPoints,winding=rawWinding.filter((_,i)=>i%4===0||i===rawWinding.length-1).map(p=>[wc[0]+p[0],wc[1]+p[1]*Math.cos(wr)-p[2]*Math.sin(wr),wc[2]+p[1]*Math.sin(wr)+p[2]*Math.cos(wr)]as const),e=[Math.cos(pc.yaw),0,Math.sin(pc.yaw)]as const,n=[-e[2],0,e[0]]as const,luff=pc.luff.points.map(p=>[pc.head[0]+e[0]*p[0]+n[0]*p[2],pc.head[1]+p[1],pc.head[2]+e[2]*p[0]+n[2]*p[2]]as const);this.setVisibleRope(pc.rope.points,[],[luff]);this.setWindingRope(winding);const active=new Set(operation.seatedPartIds),hidden=new Set(['cargo-drum-rope-inventory']);this.refreshBatches(active,hidden);this.group.userData.phase=operation.phase;this.group.userData.seconds=operation.seconds;this.group.userData.activePartIds=[...active];this.group.userData.hiddenRoles=[...hidden];this.group.userData.cable={pending:true,rope:operation.parkedCargo.rope};this.group.userData.operation=operation;}
  update(seconds:number,assembly:EiffelSummitCargoAssemblyIndex=1){this.seconds=seconds;this.assembly=assembly;if(this.disposed)return;const s=sampleEiffelSummitCargo(seconds,assembly);
    for(const t of eiffelSummitCargoRoleTransforms(s)){const o=this.roles.get(t.role);if(!o)continue;if(t.position)o.position.set(...t.position);if(t.quaternion)o.quaternion.set(...t.quaternion);}
    for(const member of s.members){const o=this.parts.get(member.partId),base=this.partBases.get(member.partId);if(!o||!base)continue;const final=this.finals.get(member.partId)!,desired=new Matrix4().compose(new Vector3(...member.pose.position),new Quaternion(...member.pose.quaternion),new Vector3(1,1,1)),sourceFinal=new Matrix4().compose(new Vector3(...final.pose.position),new Quaternion(...final.pose.quaternion),new Vector3(1,1,1));desired.multiply(sourceFinal.invert()).multiply(base).decompose(o.position,o.quaternion,o.scale);}
    if(assembly===2)for(const member of sampleEiffelSummitCargo(112,1).members){const o=this.parts.get(member.partId),base=this.partBases.get(member.partId);if(!o||!base)continue;const final=this.finals.get(member.partId)!,desired=new Matrix4().compose(new Vector3(...member.pose.position),new Quaternion(...member.pose.quaternion),new Vector3(1,1,1)),sourceFinal=new Matrix4().compose(new Vector3(...final.pose.position),new Quaternion(...final.pose.quaternion),new Vector3(1,1,1));desired.multiply(sourceFinal.invert()).multiply(base).decompose(o.position,o.quaternion,o.scale);}
    const wr=s.cable.rope.winding.drumRotation,wc=s.cable.rope.winding.drumCenter,rawWinding=s.cable.rope.winding.localPoints,winding=rawWinding.filter((_,i)=>i%4===0||i===rawWinding.length-1).map(p=>[wc[0]+p[0],wc[1]+p[1]*Math.cos(wr)-p[2]*Math.sin(wr),wc[2]+p[1]*Math.sin(wr)+p[2]*Math.cos(wr)]as const),e=[Math.cos(s.jib.yaw),0,Math.sin(s.jib.yaw)]as const,n=[-e[2],0,e[0]]as const,luff=s.luff.points.map(p=>[s.jib.head[0]+e[0]*p[0]+n[0]*p[2],s.jib.head[1]+p[1],s.jib.head[2]+e[2]*p[0]+n[2]*p[2]]as const);this.setVisibleRope(s.cable.rope.points,s.cable.rope.bridle,[luff]);this.setWindingRope(winding);
    const active=new Set(s.members.map(m=>m.partId));if(assembly===2)for(const m of sampleEiffelSummitCargo(112,1).members)active.add(m.partId);const hidden=new Set(['cargo-drum-rope-inventory',...(assembly===1?['guide-2-fixed','guide-2-north-leaf','guide-2-south-leaf','guide-3-fixed','guide-3-north-leaf','guide-3-south-leaf','climb-drive-fixed']:[])]);this.refreshBatches(active,hidden);
    this.group.userData.batchCount=this.batches.length;this.group.userData.candidate=true;this.group.userData.phase=s.phase;this.group.userData.seconds=s.seconds;this.group.userData.assembly=s.assembly;this.group.userData.activePartIds=[...active];this.group.userData.contextPartIds=[...this.contextPartIds];this.group.userData.hiddenRoles=[...hidden];this.group.userData.cable=s.cable;this.group.updateMatrixWorld(true);
  }
  dispose(){this.disposed=true;this.group.traverse(o=>{const m=o as unknown as{geometry?:{dispose():void};material?:{dispose():void}|{dispose():void}[]};m.geometry?.dispose();for(const x of Array.isArray(m.material)?m.material:m.material?[m.material]:[])x.dispose()});for(const b of this.batches)b.mesh.dispose();this.batches=[];this.ropeGeometry?.dispose();this.ropeMaterial?.dispose();this.rope=undefined;this.ropeCenterline=undefined;this.windingRope=undefined;this.finals.clear();this.roles.clear();this.parts.clear();this.partBases.clear();this.group.clear();this.group.removeFromParent();}
}
