import {sampleEiffelLongLoadFilm}from'./eiffelLongLoadFilm';
import {EIFFEL_SECOND_FLOOR_RELAY_PART_ID,type EiffelSecondFloorRelaySample}from'./eiffelSecondFloorRelay';
import type{RigidVec3 as V}from'./eiffelRigid';
export const EIFFEL_SECOND_FLOOR_RELAY_ROUTE_DURATION=126;
export const EIFFEL_SECOND_FLOOR_RELAY_DIAGONAL_LENGTH=Math.hypot(6.5,2.2);
export interface EiffelSecondFloorRelayRigDesign {readonly guideU:number;readonly guideY:number;readonly drumU:number;readonly drumY:number;readonly sheaveRadius:number;readonly drumRadius:number;readonly trolleyYOffset:number}
/** Provisional route fixture. The saved asset design record replaces only these rig coordinates. */
export const EIFFEL_SECOND_FLOOR_RELAY_PROVISIONAL_RIG:EiffelSecondFloorRelayRigDesign={guideU:7.70,guideY:125.70,drumU:10.85,drumY:116.93999938964844,sheaveRadius:.25,drumRadius:.3,trolleyYOffset:.145};
const L=EIFFEL_SECOND_FLOOR_RELAY_DIAGONAL_LENGTH,START:V=[-8.5,58.2800024414,-4],PEAK=117.70,RECEIVED=116.47999939,MASTER_OFFSET=6.882500305,HOOK_OFFSET=.325;
const ease=(x:number)=>{const t=Math.max(0,Math.min(1,x));return t*t*(3-2*t)};
const world=([u,y,v]:V):V=>[-8.5-6.5/L*u-2.2/L*v,y,-4+2.2/L*u-6.5/L*v];
function rig(cargoU:number,carrierY:number,d:EiffelSecondFloorRelayRigDesign){const trolleyU=cargoU+.25,hookY=carrierY+MASTER_OFFSET+HOOK_OFFSET,du=d.guideU-d.drumU,dy=d.guideY-d.drumY,D=Math.hypot(du,dy),tangentOffset=d.drumRadius-d.sheaveRadius,ratio=tangentOffset/D,side=Math.sqrt(1-ratio*ratio),nu=ratio*du/D+side*dy/D,ny=ratio*dy/D-side*du/D,angle=Math.atan2(ny,nu),rope:V[]=[[d.drumU+d.drumRadius*nu,d.drumY+d.drumRadius*ny,0]];for(let i=0;i<=24;i++){const a=angle+(Math.PI/2-angle)*i/24;rope.push([d.guideU+d.sheaveRadius*Math.cos(a),d.guideY+d.sheaveRadius*Math.sin(a),0])}for(let i=0;i<=24;i++){const a=Math.PI/2+Math.PI/2*i/24;rope.push([trolleyU+d.sheaveRadius*Math.cos(a),d.guideY+d.sheaveRadius*Math.sin(a),0])}rope.push([cargoU,hookY,0]);const constant=Math.sqrt(D*D-tangentOffset*tangentOffset)+d.sheaveRadius*(Math.PI-angle),deployedLength=constant+d.guideU-trolleyU+d.guideY-hookY,referenceLength=constant+d.guideU-.25+d.guideY-(START[1]+MASTER_OFFSET+HOOK_OFFSET),travel=deployedLength-referenceLength;return{rope:rope.map(world),trolley:world([trolleyU,d.guideY+d.trolleyYOffset,0]),drumAngle:travel/d.drumRadius,fixedSheaveAngle:travel/d.sheaveRadius,movingSheaveAngle:-(carrierY-START[1])/d.sheaveRadius,deployedLength};}
/** Route-only clock. Time zero is after the separately authored connector and bolt-release handoff. */
export function sampleEiffelSecondFloorRelayRoute(rawSeconds:number,design:EiffelSecondFloorRelayRigDesign=EIFFEL_SECOND_FLOOR_RELAY_PROVISIONAL_RIG):EiffelSecondFloorRelaySample&{readonly route:{readonly cargoU:number;readonly rig:ReturnType<typeof rig>}}{
 if(!Number.isFinite(rawSeconds)||Object.values(design).some(v=>!Number.isFinite(v)))throw Error('Second-floor relay route inputs must be finite');const seconds=Math.max(0,Math.min(EIFFEL_SECOND_FLOOR_RELAY_ROUTE_DURATION,rawSeconds)),lift=ease(seconds/106),traverse=ease((seconds-106)/16),lower=ease((seconds-122)/4),cargoU=L*traverse,carrierY=START[1]+(PEAK-START[1])*lift-(PEAK-RECEIVED)*lower,carrier=world([cargoU,carrierY,0]),master:V=[carrier[0],carrier[1]+MASTER_OFFSET,carrier[2]],r=rig(cargoU,carrierY,design),terminal=sampleEiffelLongLoadFilm(280),received=seconds>=126;
 const crankAngle=-2*r.drumAngle,crankOrigin:V=[-24.08,58.74000244140625,-4.69],pin:V=[crankOrigin[0]+.1*Math.cos(crankAngle),crankOrigin[1]+.1*Math.sin(crankAngle),crankOrigin[2]-.51],slider:V=[pin[0]-Math.sqrt(.5**2-(pin[1]-crankOrigin[1])**2),crankOrigin[1],crankOrigin[2]-.51],rod:V=[(pin[0]+slider[0])/2,(pin[1]+slider[1])/2,crankOrigin[2]-.51],rodAngle=Math.atan2(pin[1]-slider[1],pin[0]-slider[0]),zq=(a:number):readonly[number,number,number,number]=>[0,0,Math.sin(a/2),Math.cos(a/2)],yq=(a:number):readonly[number,number,number,number]=>[0,Math.sin(a/2),0,Math.cos(a/2)],wheelAngle=-cargoU/.115;
 const hardwareRoles=[{role:'sling-parking-saddle',position:carrier},{role:'relay-trolley',position:r.trolley},{role:'relay-drum',quaternion:zq(r.drumAngle)},{role:'relay-fixed-sheave',quaternion:zq(r.fixedSheaveAngle)},{role:'relay-moving-sheave',quaternion:zq(r.movingSheaveAngle)},{role:'relay-drive-crank',position:crankOrigin,quaternion:zq(crankAngle)},{role:'relay-drive-slider',position:slider},{role:'relay-drive-connecting-rod',position:rod,quaternion:zq(rodAngle)},...Array.from({length:4},(_,i)=>({role:`relay-wheel-${i}`,quaternion:yq(wheelAngle)}))];
 const payload:V=[carrier[0],carrier[1]+3.0762500762939453,carrier[2]];
 return{seconds,phase:seconds<106?'vertical-lift':seconds<122?'diagonal-traverse':seconds<126?'lower-to-cart':'received',partId:EIFFEL_SECOND_FLOOR_RELAY_PART_ID,ownsPayload:true,seated:false,carrierPose:{position:carrier,quaternion:[0,0,0,1]},payloadPose:{position:payload,quaternion:[0,0,0,1]},masterLinkPose:{position:master,quaternion:[0,0,0,1]},retainedFirstHoistRope:terminal.worldRope,secondHoist:{worldRope:r.rope,attached:true,driveAdmitted:false},hardwareRoles,carrierSupport:received?'upper-receiver':'tackle',slingSupport:'tackle',cartPose:{position:[-8.5,57.94000244140625,-4],quaternion:[0,0,0,1]},cartSupport:'first-floor',cartAttached:false,fastening:{installed:0,required:4,released:true},route:{cargoU,rig:r}};
}
