import { sampleEiffelJointCampaign } from './eiffelJointCampaign';
import type { EiffelGroundRiggerArm, EiffelGroundRiggerContact, EiffelGroundRiggerFoot, EiffelGroundRiggerLimb, EiffelGroundRiggerPhase } from './eiffelGroundRiggers';
import { eiffelTerrainHeightAt } from './eiffelTerrain';
import type { RigidQuat, RigidVec3 as V } from './eiffelRigid';

export type EiffelJointRiggerId='joint-slinger-north'|'joint-slinger-south';
export interface EiffelJointRiggerWorker {readonly id:EiffelJointRiggerId;readonly job:'joint-ground-slinger';readonly phase:EiffelGroundRiggerPhase;readonly leftFoot:EiffelGroundRiggerFoot;readonly rightFoot:EiffelGroundRiggerFoot;readonly leftLeg:EiffelGroundRiggerLimb;readonly rightLeg:EiffelGroundRiggerLimb;readonly hip:V;readonly shoulderCenter:V;readonly torso:readonly[V,V];readonly head:{readonly center:V;readonly radius:number};readonly arms:{readonly left:EiffelGroundRiggerArm;readonly right:EiffelGroundRiggerArm};readonly contact:EiffelGroundRiggerContact}
export interface EiffelJointRiggerSample {readonly seconds:number;readonly phase:EiffelGroundRiggerPhase;readonly activeLoadIndex:0|1;readonly workers:readonly[EiffelJointRiggerWorker,EiffelJointRiggerWorker]}
const add=(a:V,b:V):V=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],sub=(a:V,b:V):V=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],mul=(a:V,s:number):V=>[a[0]*s,a[1]*s,a[2]*s],mix=(a:V,b:V,t:number):V=>add(a,mul(sub(b,a),t));
const clamp=(x:number)=>Math.max(0,Math.min(1,x)),smooth=(x:number)=>{const t=clamp(x);return t*t*(3-2*t)};
function solveArm(shoulder:V,hand:V,bend:number):EiffelGroundRiggerArm{const upperLength=.38 as const,forearmLength=.4 as const,d=sub(hand,shoulder),distance=Math.hypot(...d);if(distance>upperLength+forearmLength+1e-9||distance<forearmLength-upperLength-1e-9)throw Error(`Joint slinger target unreachable (${distance.toFixed(3)} m)`);const u=mul(d,1/distance),along=(upperLength**2-forearmLength**2+distance**2)/(2*distance),height=Math.sqrt(Math.max(0,upperLength**2-along**2));let n:V=[-u[1],u[0],0],length=Math.hypot(...n);n=length<1e-8?[0,0,bend]:mul(n,bend/length);return{shoulder,elbow:add(add(shoulder,mul(u,along)),mul(n,height)),hand,upperLength,forearmLength};}
const anchor=sampleEiffelJointCampaign(14),anchorLugs=anchor.rigging.lugs,yaw=2*Math.atan2(anchor.loads[0].pose.quaternion[1],anchor.loads[0].pose.quaternion[3]),outboard:V=[Math.cos(yaw),0,-Math.sin(yaw)],along:V=[Math.sin(yaw),0,Math.cos(yaw)],footQ:RigidQuat=[0,Math.sin(yaw/2),0,Math.cos(yaw/2)];
const point=(origin:V,x:number,y:number,z:number):V=>{const p=add(add(origin,mul(outboard,x)),mul(along,z));return[p[0],eiffelTerrainHeightAt(p[0],p[2])+y,p[2]]};
function worker(index:0|1,seconds:number,phase:EiffelGroundRiggerPhase,cycle:number):EiffelJointRiggerWorker{
 const campaign=sampleEiffelJointCampaign(seconds),origin=anchorLugs[index],ground=eiffelTerrainHeightAt(origin[0],origin[2]),lean=smooth(cycle-12)*(1-smooth((cycle-14)/.8));
 const hip=point(origin,1.312,.98,0),waist=point(origin,1.312,1.27,0),shoulder=point(origin,1.162+(.682-1.162)*lean,1.55,0),clearHand=point(origin,1.192,1.22,index?-.18:.18);
 let target=clearHand,kind:EiffelGroundRiggerContact['kind']='none';const loose=campaign.rigging.slings[index]!.points[2],lug=campaign.rigging.lugs[index]!;
 if(cycle>=12&&cycle<13)target=mix(clearHand,loose,smooth(cycle-12));else if(cycle>=13&&cycle<14){target=loose;kind='loose-sling-end';}else if(cycle===14){target=lug;kind='pickup-lug';}else if(cycle>14&&cycle<14.6)target=mix(lug,clearHand,smooth((cycle-14)/.6));
 const working=solveArm(shoulder,target,-1),idleShoulder=point(shoulder,0,shoulder[1]-ground,index?-.12:.12),idleHand=point(origin,1.212,1.3,index?-.26:.26),idle=solveArm(idleShoulder,idleHand,1);
 const foot=(dz:number):EiffelGroundRiggerFoot=>{const center=point(origin,1.332,.06,dz);return{center,size:[.28,.12,.14],quaternion:footQ}},leftFoot=foot(-.18),rightFoot=foot(.18),knee=(foot:EiffelGroundRiggerFoot,side:number)=>mix(foot.center,point(origin,1.312,.48,side*.08),.5);
 const leftLeg={start:leftFoot.center,joint:knee(leftFoot,-1),end:point(origin,1.312,.98,-.1)},rightLeg={start:rightFoot.center,joint:knee(rightFoot,1),end:point(origin,1.312,.98,.1)};
 return{id:index?'joint-slinger-south':'joint-slinger-north',job:'joint-ground-slinger',phase,leftFoot,rightFoot,leftLeg,rightLeg,hip,shoulderCenter:shoulder,torso:[waist,shoulder],head:{center:point(origin,1.162+(.682-1.162)*lean-.08,1.77,0),radius:.17},arms:index?{left:idle,right:working}:{left:working,right:idle},contact:{kind,target:kind==='none'?null:target,residual:kind==='none'?null:0}};
}
export function sampleEiffelJointRiggers(rawSeconds:number):EiffelJointRiggerSample{if(!Number.isFinite(rawSeconds))throw Error('Joint rigger time must be finite');const seconds=Math.max(0,Math.min(135,rawSeconds)),activeLoadIndex:0|1=seconds<65?0:1,cycle=activeLoadIndex===0?seconds:seconds-68;const phase:EiffelGroundRiggerPhase=cycle<12?'waiting':cycle<13?'reach':cycle<=14?'clip':cycle<14.6?'release':activeLoadIndex===0?'waiting':'clear';return{seconds,phase,activeLoadIndex,workers:[worker(0,seconds,phase,cycle),worker(1,seconds,phase,cycle)]};}
