import { EIFFEL_SUMMIT_CARGO_DURATION, eiffelSummitCargoRoleTransforms, sampleEiffelSummitCargo, type EiffelSummitCargoSample } from './eiffelSummitCargo';
import { EIFFEL_SUMMIT_GIN_POLE_CLIMB_DURATION, eiffelSummitGinPoleRoleTransforms, sampleEiffelSummitGinPoleClimb, type EiffelSummitGinPoleClimbSample } from './eiffelSummitGinPoleClimb';
import { EIFFEL_SUMMIT_CARGO_SIDE, solveEiffelSummitCargoRope } from './eiffelSummitCargoRope';
import { solveEiffelSummitLuff } from './eiffelSummitLuff';

export const EIFFEL_SUMMIT_TACKLE_RETURN_DURATION = 25;
export const EIFFEL_SUMMIT_OPERATION_DURATION = EIFFEL_SUMMIT_CARGO_DURATION * 2 + EIFFEL_SUMMIT_GIN_POLE_CLIMB_DURATION + EIFFEL_SUMMIT_TACKLE_RETURN_DURATION;
export type EiffelSummitOperationPhase = 'cargo-c001' | 'pole-climb' | 'tackle-return' | 'cargo-c002' | 'complete';
export interface EiffelSummitOperationSample {
  readonly seconds:number; readonly phase:EiffelSummitOperationPhase;
  readonly cargo:EiffelSummitCargoSample|null; readonly climb:EiffelSummitGinPoleClimbSample|null;
  /** Empty cargo tackle parked beside the head while the pole climbs. */
  readonly parkedCargo:null|{readonly head:readonly[number,number,number];readonly block:readonly[number,number,number];readonly yaw:number;readonly pitch:number;readonly rope:ReturnType<typeof solveEiffelSummitCargoRope>;readonly luff:ReturnType<typeof solveEiffelSummitLuff>};
  readonly seatedPartIds:readonly string[]; readonly activeRoleTransforms:readonly {role:string;position?:readonly[number,number,number];quaternion?:readonly[number,number,number,number]}[];
  readonly fixedCargoDriveVisible:true; readonly oldGuidesVisible:true; readonly newGuidesVisible:boolean;
  readonly provenance:{readonly groundToTerraceAdmitted:false;readonly secondStockAttachmentAdmitted:false;readonly reason:'earlier-ground-to-terrace-chain-unresolved'};
}

/** Candidate-only mechanism sequencing adapter. It does not include workers, alter the production clock, or claim the stock's arrival on the terrace. */
export function sampleEiffelSummitOperation(rawSeconds:number):EiffelSummitOperationSample {
  if(!Number.isFinite(rawSeconds))throw Error('Eiffel summit operation time must be finite');
  const seconds=Math.max(0,Math.min(EIFFEL_SUMMIT_OPERATION_DURATION,rawSeconds));
  let phase:EiffelSummitOperationPhase,cargo:EiffelSummitCargoSample|null=null,climb:EiffelSummitGinPoleClimbSample|null=null,seatedPartIds:string[]=[],parkedCargo:EiffelSummitOperationSample['parkedCargo']=null;
  if(seconds<EIFFEL_SUMMIT_CARGO_DURATION){phase='cargo-c001';cargo=sampleEiffelSummitCargo(seconds,1);}
  else if(seconds<EIFFEL_SUMMIT_CARGO_DURATION+EIFFEL_SUMMIT_GIN_POLE_CLIMB_DURATION){phase='pole-climb';climb=sampleEiffelSummitGinPoleClimb(seconds-EIFFEL_SUMMIT_CARGO_DURATION);seatedPartIds=['summit-crown-m072-c001','summit-crown-m074-c000','summit-crown-m075-c000'];const head:[number,number,number]=[-.9,climb.poleBottomY+6.15,0],parkTarget:[number,number,number]=[head[0]-1,head[1]-1.5,head[2]-.8],landed=sampleEiffelSummitCargo(EIFFEL_SUMMIT_CARGO_DURATION,1).jib.hookPoint,u=Math.max(0,Math.min(1,climb.seconds/5)),ease=u*u*(3-2*u),startDx=landed[0]-head[0],startDz=landed[2]-head[2],endDx=parkTarget[0]-head[0],endDz=parkTarget[2]-head[2],startRadius=Math.hypot(startDx,startDz),endRadius=Math.hypot(endDx,endDz),startAngle=Math.atan2(startDz,startDx),rawAngle=Math.atan2(endDz,endDx),angleDelta=((rawAngle-startAngle+Math.PI*3)%(Math.PI*2))-Math.PI,angle=startAngle+angleDelta*ease,radius=startRadius+(endRadius-startRadius)*ease,block:[number,number,number]=[head[0]+radius*Math.cos(angle),landed[1]+(parkTarget[1]-landed[1])*ease,head[2]+radius*Math.sin(angle)],dx=block[0]-head[0],dz=block[2]-head[2],rho=Math.hypot(dx,dz),projected=Math.sqrt(rho*rho-EIFFEL_SUMMIT_CARGO_SIDE**2),yaw=Math.atan2(dz,dx)-Math.atan2(EIFFEL_SUMMIT_CARGO_SIDE,projected),pitch=Math.acos((projected-.3)/5.7);parkedCargo={head,block,yaw,pitch,rope:solveEiffelSummitCargoRope({assembly:'parked-climb',heel:head,boomYaw:yaw,boomPitch:pitch,lowerBlockCenter:block}),luff:solveEiffelSummitLuff(pitch)};}
  else if(seconds<EIFFEL_SUMMIT_CARGO_DURATION+EIFFEL_SUMMIT_GIN_POLE_CLIMB_DURATION+EIFFEL_SUMMIT_TACKLE_RETURN_DURATION){phase='tackle-return';seatedPartIds=['summit-crown-m072-c001','summit-crown-m074-c000','summit-crown-m075-c000'];const elapsed=seconds-EIFFEL_SUMMIT_CARGO_DURATION-EIFFEL_SUMMIT_GIN_POLE_CLIMB_DURATION,head=sampleEiffelSummitCargo(0,2).jib.head,start:[number,number,number]=[head[0]-1,head[1]-1.5,head[2]-.8];let block:[number,number,number];if(elapsed<5){const destination=sampleEiffelSummitCargo(76,2).jib.hookPoint,u=elapsed/5,ease=u*u*(3-2*u),a0=Math.atan2(start[2]-head[2],start[0]-head[0]),a1=Math.atan2(destination[2]-head[2],destination[0]-head[0]),da=((a1-a0+Math.PI*3)%(Math.PI*2))-Math.PI,r0=Math.hypot(start[0]-head[0],start[2]-head[2]),r1=Math.hypot(destination[0]-head[0],destination[2]-head[2]),r=r0+(r1-r0)*ease,a=a0+da*ease;block=[head[0]+r*Math.cos(a),start[1]+(destination[1]-start[1])*ease,head[2]+r*Math.sin(a)];}else block=[...sampleEiffelSummitCargo(76*(1-(elapsed-5)/20),2).jib.hookPoint];const dx=block[0]-head[0],dz=block[2]-head[2],rho=Math.hypot(dx,dz),projected=Math.sqrt(rho*rho-EIFFEL_SUMMIT_CARGO_SIDE**2),yaw=Math.atan2(dz,dx)-Math.atan2(EIFFEL_SUMMIT_CARGO_SIDE,projected),pitch=Math.acos((projected-.3)/5.7);parkedCargo={head,block,yaw,pitch,rope:solveEiffelSummitCargoRope({assembly:'return-to-c002',heel:head,boomYaw:yaw,boomPitch:pitch,lowerBlockCenter:block}),luff:solveEiffelSummitLuff(pitch)};}
  else if(seconds<EIFFEL_SUMMIT_OPERATION_DURATION){phase='cargo-c002';cargo=sampleEiffelSummitCargo(seconds-EIFFEL_SUMMIT_CARGO_DURATION-EIFFEL_SUMMIT_GIN_POLE_CLIMB_DURATION-EIFFEL_SUMMIT_TACKLE_RETURN_DURATION,2);seatedPartIds=['summit-crown-m072-c001','summit-crown-m074-c000','summit-crown-m075-c000'];}
  else{phase='complete';cargo=sampleEiffelSummitCargo(EIFFEL_SUMMIT_CARGO_DURATION,2);seatedPartIds=['summit-crown-m072-c001','summit-crown-m074-c000','summit-crown-m075-c000','summit-crown-m072-c002','summit-crown-m076-c000'];}
  const cargoTransforms=parkedCargo?[{role:'cargo-jib-yaw',quaternion:[0,Math.sin(-parkedCargo.yaw/2),0,Math.cos(-parkedCargo.yaw/2)] as const},{role:'cargo-jib-pitch',position:[.3,0,0] as const,quaternion:[0,0,Math.sin(parkedCargo.pitch/2),Math.cos(parkedCargo.pitch/2)] as const},{role:'cargo-travelling-block',position:parkedCargo.block,quaternion:[0,Math.sin(-parkedCargo.yaw/2),0,Math.cos(-parkedCargo.yaw/2)] as const},{role:'cargo-drum-carriage',position:parkedCargo.rope.winding.drumCenter},{role:'cargo-winch-drum',position:parkedCargo.rope.winding.drumCenter,quaternion:[Math.sin(parkedCargo.rope.winding.drumRotation/2),0,0,Math.cos(parkedCargo.rope.winding.drumRotation/2)] as const},{role:'cargo-output-shaft',quaternion:[Math.sin(parkedCargo.rope.winding.drumRotation/2),0,0,Math.cos(parkedCargo.rope.winding.drumRotation/2)] as const},{role:'cargo-output-gear',quaternion:[Math.sin(parkedCargo.rope.winding.drumRotation/2),0,0,Math.cos(parkedCargo.rope.winding.drumRotation/2)] as const},{role:'cargo-input-crank',quaternion:[Math.sin(-parkedCargo.rope.winding.drumRotation),0,0,Math.cos(-parkedCargo.rope.winding.drumRotation)] as const},{role:'cargo-ratchet-wheel',quaternion:[Math.sin(parkedCargo.rope.winding.drumRotation/2),0,0,Math.cos(parkedCargo.rope.winding.drumRotation/2)] as const},{role:'cargo-traverse-cam',quaternion:[Math.sin(parkedCargo.rope.winding.camRotation/2),0,0,Math.cos(parkedCargo.rope.winding.camRotation/2)] as const},{role:'cargo-traverse-follower',quaternion:[0,Math.sin(Math.atan2(parkedCargo.rope.winding.followerTangent[0],parkedCargo.rope.winding.followerTangent[2])/2),0,Math.cos(Math.atan2(parkedCargo.rope.winding.followerTangent[0],parkedCargo.rope.winding.followerTangent[2])/2)] as const},{role:'cargo-luff-drum',quaternion:[0,0,Math.sin(parkedCargo.luff.drive.drumAngle/2),Math.cos(parkedCargo.luff.drive.drumAngle/2)] as const},{role:'cargo-luff-input',quaternion:[0,0,Math.sin(-parkedCargo.luff.drive.drumAngle),Math.cos(-parkedCargo.luff.drive.drumAngle)] as const}]:[];
  return{seconds,phase,cargo,climb,parkedCargo,seatedPartIds,activeRoleTransforms:cargo?eiffelSummitCargoRoleTransforms(cargo):parkedCargo?[...eiffelSummitGinPoleRoleTransforms(climb??sampleEiffelSummitGinPoleClimb(EIFFEL_SUMMIT_GIN_POLE_CLIMB_DURATION)),...cargoTransforms]:[],fixedCargoDriveVisible:true,oldGuidesVisible:true,newGuidesVisible:seconds>=EIFFEL_SUMMIT_CARGO_DURATION,provenance:{groundToTerraceAdmitted:false,secondStockAttachmentAdmitted:false,reason:'earlier-ground-to-terrace-chain-unresolved'}};
}
