import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import type {EiffelKitManifest,EiffelKitPart} from '../src/data/eiffelKitTypes';
import {eiffelConvexBox,eiffelConvexPenetration,eiffelConvexSolid,eiffelConvexTranslationSweep,type EiffelConvexSolid} from '../src/engine/eiffelConvex';
import {eiffelSolidBox,type EiffelSolidBox} from '../src/engine/eiffelOccupancy';
import {interpolateRigidPose,rotateRigidVector,type RigidPose,type RigidVec3 as V} from '../src/engine/eiffelRigid';

const folder='artifacts/eiffel-summit-stock-2026-09-08/',manifest=JSON.parse(readFileSync('public/models/eiffel-construction-kit/tower-kit.manifest.json','utf8')) as EiffelKitManifest;
const shaft=JSON.parse(readFileSync('artifacts/eiffel-ground-supply-2026-09-08/central-shaft-rotated-probe.json','utf8')) as {freeze:number;results:{partId:string;route:{high:RigidPose}}[]};
const stock=JSON.parse(readFileSync(folder+'stock-plan.json','utf8')) as {racks:{id:string;center:[number,number];depth:number;yaw:number;usableDepth:number}[];placements:{partId:string;rackId:string;shelfIndex:0|1;bin:{x:number;z:number;width:number;depth:number};pose:RigidPose}[]};
type Prism={id:string;rackId:string;role:string;vertices:V[]};const prisms=JSON.parse(readFileSync(folder+'rack-occupancy.json','utf8')) as Prism[];
const faces=[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]] as const,parts=new Map(manifest.parts.map(p=>[p.id,p])),highs=new Map(shaft.results.map(r=>[r.partId,r.route.high])),racks=new Map(stock.racks.map(r=>[r.id,r]));
const fixed=manifest.parts.filter(p=>p.stage<=56).map(p=>({id:p.id,box:eiffelSolidBox({...p,shape:'box'},p.finalPose),solid:eiffelConvexBox(eiffelSolidBox({...p,shape:'box'},p.finalPose))}));
const rackSolids=prisms.map(p=>({id:p.id,prism:p,solid:eiffelConvexSolid(p.vertices,faces)}));
const localRadius=(part:EiffelKitPart)=>Math.max(...[-1,1].flatMap(x=>[-1,1].flatMap(y=>[-1,1].map(z=>Math.hypot(x<0?part.localBounds.min[0]:part.localBounds.max[0],y<0?part.localBounds.min[1]:part.localBounds.max[1],z<0?part.localBounds.min[2]:part.localBounds.max[2])))));
function sphereBox(center:V,radius:number,box:EiffelSolidBox){const d:V=[center[0]-box.center[0],center[1]-box.center[1],center[2]-box.center[2]];let squared=0;for(let i=0;i<3;i++){const projection=d[0]*box.axes[i]![0]+d[1]*box.axes[i]![1]+d[2]*box.axes[i]![2],outside=Math.max(0,Math.abs(projection)-box.half[i]!);squared+=outside*outside;}return squared<radius*radius-1e-10;}
function prismBox(prism:Prism):EiffelSolidBox{const min=[0,1,2].map(k=>Math.min(...prism.vertices.map(v=>v[k]!))) as V,max=[0,1,2].map(k=>Math.max(...prism.vertices.map(v=>v[k]!))) as V;return{center:[(min[0]+max[0])/2,(min[1]+max[1])/2,(min[2]+max[2])/2],half:[(max[0]-min[0])/2,(max[1]-min[1])/2,(max[2]-min[2])/2],axes:[[1,0,0],[0,1,0],[0,0,1]]};}
const rackBoxes=rackSolids.map(x=>({...x,box:prismBox(x.prism)}));
const innerSign=(rack:{center:[number,number];yaw:number})=>{const axis=rotateRigidVector([0,Math.sin(rack.yaw/2),0,Math.cos(rack.yaw/2)],[1,0,0]);return Math.sign(axis[0]*-rack.center[0]+axis[2]*-rack.center[1])||1;};
const loadPriority=new Map([['beacon-window-08-m002-c000',-2],['beacon-window-07-m002-c000',-1],['beacon-window-12-m002-c000',-2],['beacon-window-11-m002-c000',-1]]);
const ordered=stock.placements.slice().sort((a,b)=>a.shelfIndex-b.shelfIndex||a.rackId.localeCompare(b.rackId)||innerSign(racks.get(a.rackId)!)*(a.bin.z+a.bin.depth/2)-innerSign(racks.get(b.rackId)!)*(b.bin.z+b.bin.depth/2)||((loadPriority.get(a.partId)??0)-(loadPriority.get(b.partId)??0))||a.partId.localeCompare(b.partId));
const stored:{id:string;solid:EiffelConvexSolid}[]=[],results=[];
const classify=(item:{id:string;solid:EiffelConvexSolid})=>'prism'in item?'rack':'box'in item?'completed-iron':'stored';
function auditLeg(part:EiffelKitPart,start:RigidPose,end:RigidPose,leg:string,context:({id:string;solid:EiffelConvexSolid}|typeof fixed[number]|typeof rackSolids[number])[],placement:typeof ordered[number]){
 const moving=eiffelConvexTranslationSweep(eiffelConvexBox(eiffelSolidBox(part,start)),[end.position[0]-start.position[0],end.position[1]-start.position[1],end.position[2]-start.position[2]]),failures:string[]=[];
 for(const item of context){const depth=eiffelConvexPenetration(moving,item.solid);if(depth<=1e-5)continue;const prism='prism'in item?item.prism:null;const intended=(leg==='shelf-insertion'||leg==='lengthwise-slide')&&prism?.rackId===placement.rackId&&prism.role==='shelf'&&prism.id.endsWith(`shelf-${placement.shelfIndex}`)&&depth<=1e-4;if(!intended)failures.push(`${leg}:${classify(item)}:${item.id}`);}
 return failures;
}
for(const [order,placement] of ordered.entries()){
 const part=parts.get(placement.partId)!,upright=highs.get(part.id)!,rack=racks.get(placement.rackId)!,sign=innerSign(rack),q=placement.pose.quaternion,radius=localRadius(part),flatHigh:RigidPose={position:[upright.position[0],287,upright.position[2]],quaternion:q};
 const depth=part.transportSize[0],desired=sign*(rack.depth/2+depth/2+.08),targetLocal=placement.bin.z+placement.bin.depth/2-rack.usableDepth/2,delta=desired-targetLocal,transverse=rotateRigidVector(q,[1,0,0]),longitudinal=rotateRigidVector(q,[0,0,1]),baseApproach:RigidPose={position:[placement.pose.position[0]+transverse[0]*delta,placement.pose.position[1],placement.pose.position[2]+transverse[2]*delta],quaternion:q};
 const context=[...fixed,...rackSolids,...stored],rotationFailure=new Set<string>();
 for(const item of fixed)if(sphereBox(upright.position,radius,item.box))rotationFailure.add(`rotation:completed-iron:${item.id}`);for(const item of rackBoxes)if(sphereBox(upright.position,radius,item.box))rotationFailure.add(`rotation:rack:${item.id}`);for(const item of stored)if(sphereBox(upright.position,radius,eiffelSolidBox({localBounds:{min:item.solid.min,max:item.solid.max}},{position:[0,0,0],quaternion:[0,0,0,1]})))rotationFailure.add(`rotation:stored:${item.id}`);
 let sampledRotationClear=true;for(let i=0;i<=64;i++){const pose=interpolateRigidPose(upright,flatHigh,i/64),moving=eiffelConvexBox(eiffelSolidBox(part,pose));if(context.some(x=>eiffelConvexPenetration(moving,x.solid)>1e-5)){sampledRotationClear=false;break;}}
 let chosen:{offset:number;above:RigidPose;outside:RigidPose;intermediate:RigidPose;failures:string[]}|undefined;
 for(const signedOffset of [0,.2,-.2,.4,-.4,.6,-.6,.8,-.8,1,-1]){
  const towardCenter=Math.sign(-(placement.pose.position[0]-rack.center[0])*longitudinal[0]-(placement.pose.position[2]-rack.center[1])*longitudinal[2])||1,offset=signedOffset===0?0:towardCenter*signedOffset;
  const outside:RigidPose={position:[baseApproach.position[0]+longitudinal[0]*offset,baseApproach.position[1],baseApproach.position[2]+longitudinal[2]*offset],quaternion:q},above:RigidPose={position:[outside.position[0],287,outside.position[2]],quaternion:q},intermediate:RigidPose={position:[placement.pose.position[0]+longitudinal[0]*offset,placement.pose.position[1],placement.pose.position[2]+longitudinal[2]*offset],quaternion:q};
  const failures=[...rotationFailure,...auditLeg(part,flatHigh,above,'lateral-high',context,placement),...auditLeg(part,above,outside,'descent-outside',context,placement),...auditLeg(part,outside,intermediate,'shelf-insertion',context,placement),...auditLeg(part,intermediate,placement.pose,'lengthwise-slide',context,placement)];
  if(!chosen||failures.length<chosen.failures.length)chosen={offset,above,outside,intermediate,failures};if(failures.length===0)break;
 }
 const final=eiffelConvexBox(eiffelSolidBox(part,placement.pose));stored.push({id:part.id,solid:final});const dogleg=Math.abs(chosen!.offset)>1e-9;
 results.push({partId:part.id,order,rackId:placement.rackId,shelfIndex:placement.shelfIndex,innerSide:sign<0?'negative-depth':'positive-depth',poses:{upright,flatHigh,aboveRack:chosen!.above,outsideShelf:chosen!.outside,intermediateShelf:chosen!.intermediate,stock:placement.pose},dogleg:{used:dogleg,longitudinalOffset:chosen!.offset,requires:'Authored rollers or equivalent support are required for the transverse insertion and lengthwise slide; this audit does not admit that mechanism.'},boundingSphereRadius:radius,conservativeRotationClear:![...rotationFailure].length,sampledSlerpClearDiagnostic:sampledRotationClear,clear:chosen!.failures.length===0,failures:chosen!.failures});
}
const reasonCounts=Object.fromEntries([...new Set(results.flatMap(r=>r.failures.map(f=>f.split(':').slice(0,2).join(':'))))].sort().map(reason=>[reason,results.reduce((sum,r)=>sum+r.failures.filter(f=>f.startsWith(reason+':')).length,0)]));
const summary={productionReady:false,envelopeOnly:true,freeze:shaft.freeze,total:results.length,clear:results.filter(r=>r.clear).length,rejected:results.filter(r=>!r.clear).length,reasonCounts,lowerShelfFirst:true,loadingRule:'Each shelf loads far-to-near from its rack side facing the central walking strip. Blocked straight approaches try bounded longitudinal doglegs of 0.2 to 1.0 m before exact final sliding.',limits:['In-place rotation uses a bounding-sphere envelope as the admission gate. Sampled SLERP is diagnostic only and cannot admit a failed sphere check.','Cargo and curved tower members use conservative local-bound envelopes. Dogleg routes require authored rollers or equivalent support and are geometry-only. No crane, rope, cradle, worker, strength or production readiness claim.']};mkdirSync(folder,{recursive:true});writeFileSync(folder+'handoff-audit.json',JSON.stringify({summary,results},null,2)+'\n');console.log(JSON.stringify(summary,null,2));
